### ISSUE TITLE
Tearing support

### ISSUE THREAD

**Issue by CosmicFusion** [labwc/labwc#1026]
Please:

* Enable tearing support for wayland surfaces
* Enable tearing support for xwayland surfaces (https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/665)

**Comment by Consolatis** [comment]
Labwc is using the wlroots scene graph abstraction since labwc 0.6.
As such we are not doing any own rendering anymore and a feature like that has to be available via wlroots itself (and likely the scene graph implementation in there as well).

As far as I see it is not implemented in wlroots (neither in the currently used wlroots 0.16 branch nor in the latest master branch). Any work implementing this feature thus has to start at wlroots:
- https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3249
- https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3871

**Comment by Ph42oN** [comment]
I made patch to enable tearing on wlroots 0.16, you can use it if you dont mind tearing on desktop: https://gitlab.com/Ph42oN/wlroots-async-pageflip

**Comment by johanmalm** [comment]
@Ph42oN Nice! I've never really looked at this, so can't offer much comment at a glance.
Did you want to socialize it on the wlroots IRC channel to get more eyes on it?

@emersion Appreciate any brief/quick thoughts on this.

**Comment by Ph42oN** [comment]
It goes against the "every frame is perfect" even more than tearing protocol, as this makes me get tearing even on desktop. This is basicly just parts of tearing protocol patch backported to 0.16 and simplified to always enable async pageflips if supported. I did it as i thought that it will be a while until we can get tearing protocol support on labwc as the patch is for wlroots 0.17.

**Comment by Ph42oN** [comment]
Now that labwc works with wlroots 0.17, i made [patch for labwc that adds option to enable tearing](https://github.com/labwc/labwc/commit/25a73b8dd601b27ec8c159220c85541aced93060). Now it just enables tearing everywhere, but from here we can start working on proper tearing implementation. https://github.com/labwc/labwc/commit/25a73b8dd601b27ec8c159220c85541aced93060

**Comment by johanmalm** [comment]
Thanks. Will review after releasing `0.7.0`

**Comment by Ph42oN** [comment]
Im thinking i want to do some changes, like making it use values like true, false or fullscreen instead of numbers, maybe make it function that can be used for other options too. I can make PR after this.

Anyways this currently does not support actual tearing protocol, that needs some more work to implement, and when this enables it for fullscreen on my main monitor my 2nd monitor also starts tearing. Would you like to merge it like this?

**Comment by ahesford** [comment]
#1390
