### ISSUE TITLE
Menu items can no longer be activated on xfce4-panel

### ISSUE THREAD

**Issue by Tamaranch** [labwc/labwc#1030]
Clicking on a menu item closes the menu but nothing happens (any item in any menu, e.g. opening panel preferences from a context menu). I've identified this commit as the culprit: 3111c57d6f18d07e1e8b64e2ce396d15efc73b5c.

**Comment by Consolatis** [comment]
Ref:
- #1020

If you are up for testing, does adding a check for the layer surface to the condition fix it?
```c
	if (ctx.type != LAB_SSD_CLIENT && ctx.type != LAB_SSD_LAYER_SURFACE
			&& wlr_seat_pointer_has_grab(seat->seat)) {
		[..]
	}
```

**Comment by Tamaranch** [comment]
> does adding a check for the layer surface to the condition fix it?

No, it doesn't.

> does xfce4-panel happen to have custom context menus rather than the usual GTK ones?

No it uses GtkMenu but it has keyboard interactivity set to on-demand, maybe that matters?

**Comment by Consolatis** [comment]
> > does adding a check for the layer surface to the condition fix it?
>
> No, it doesn't.

Hm.. I don't have a recent xfce4-panel installation around (still on Debian oldstable).
We'd need to know what `ctx.type` is triggering the `wlr_seat_pointer_end_grab()` call and the proper solution would then likely be to figure out why that type isn't `LAB_SSD_CLIENT` or `LAB_SSD_LAYER_SURFACE`.
Maybe @johanmalm could help with some debugging here?

For a quick manual fix it is likely enough to revert 3111c57d6f18d07e1e8b64e2ce396d15efc73b5c for now so popup grabs are only killed when clicking on the empty desktop (or other application surfaces).

**Comment by Tamaranch** [comment]
> For a quick manual fix it is likely enough to revert https://github.com/labwc/labwc/commit/3111c57d6f18d07e1e8b64e2ce396d15efc73b5c

I can confirm it fixes the issue.

**Comment by johanmalm** [comment]
Thanks for reporting.

> Hm.. I don't have a recent xfce4-panel installation around (still on Debian oldstable). We'd need to know what `ctx.type` is triggering the `wlr_seat_pointer_end_grab()` call and the proper solution would then likely be to figure out why that type isn't `LAB_SSD_CLIENT` or `LAB_SSD_LAYER_SURFACE`. Maybe @johanmalm could help with some debugging here?

Interestingly xfce4-panel and gtk-layer-demo popups both have ctx.type == 0 (=LAB_SSD_NONE). So as an easy fix we could just check against that. 

It appears that these have no node-descriptors which is weird though because they are created in `src/layers.c`.

@Consolatis can you find a client that ever gets to `LAB_LAYER_{SURFACE/POPUP}` in `get_cursor_context()`

**Comment by Consolatis** [comment]
After some debugging via IRC between malm and me the issue here seems to be some change in either GTK or GTK-layershell in regards to using subsurfaces vs xdg_popups for menus. My system seems to always use xdg_popup and thus I couldn't reproduce the issue at all. More modern versions instead seem to (at least sometimes) use subsurfaces for menus instead.

We didn't yet manage to find a proper solution but at least we know where to look now.
