### ISSUE TITLE
bemenu stays in fullscreen window

### ISSUE THREAD

**Issue by Bezzumnbiu** [labwc/labwc#1040]
If you start a fullscreen application and go to another workspace and run bemenu/wofi, the focus stays on the fullscreen application. That is, the launcher will not be visible, but it will read the input

To replicate the problem, launch the application, go to full screen mode through the keyboard shortcut. Call the launcher in any convenient way

**Comment by johanmalm** [comment]
Fullscreen clients are shown between the top and overlay layers.

So if you want a layer-shell client to render above a fullscreen client, you have to set its config to layer=overlay.

If I misunderstood your question, please say.

Ref:

https://github.com/labwc/labwc/blob/206db43786e066f7de3755a11263a971b4ed77be/src/server.c#L293

https://github.com/labwc/labwc/blob/206db43786e066f7de3755a11263a971b4ed77be/src/view.c#L872

**Comment by Bezzumnbiu** [comment]
The fact is that applications that work in the same workspace are correct. I mean if I start the game on workspace 1 then go to workspace 2 and start bemenu, then bemenu starts on workspace 1 instead of 2

**Comment by Bezzumnbiu** [comment]
A funny story is that dmenu_run, which is launched from under xwayland, is displayed correctly, and forks on wayland are "hidden" where the fullscreen application is located.

I'm trying to convey that a full screen application takes away launchers, in particular wofi / bemenu

**Comment by Consolatis** [comment]
I think the reason is that we hide layershell clients in the "top" layer whenever some window uses fullscreen.
This is an implementation detail. We could fix this specific case by reacting to workspace switches and disabling/re-enabling the top layer based on having a fullscreen window on the target workspace.

In the meantime I agree with @johanmalm and suggest to configure your menu client to use the "overlay" layer rather than the "top" one. That also has the benefit that it would show up above fullscreen windows within the current workspace.

**Comment by xxhh1112** [comment]
qqq

**Comment by johanmalm** [comment]
Fixed by https://github.com/labwc/labwc/commit/13d0b142443d6198cf8dc4dcebd2dde0c06b014c
