### ISSUE TITLE
Different app_id in OSD and windowRule

### ISSUE THREAD

**Issue by kyak** [labwc/labwc#1073]
When using Alt-Tab to display OSD (windowSwitcher), I can see that that Telegram app_id is `desktop`.

However, when trying to match this app_id using `identifier` in `windowRule`, the match doesn't happen.

I used waybar to figure out the Telegram app_id, which is apparently `org.telegram.desktop`.

So this now works (matches):

```
    <windowRule identifier="org.telegram.desktop" serverDecoration="no">
      <action name="SnapToEdge" direction="right"/>
    </windowRule>
```

It seems like OSD and windowRule use different approaches to getting `app_id/identifier`.

Can they be consistent with each other?

What is the proper way to get `app_id` in labwc anyway in order to create window rules?

**Comment by Consolatis** [comment]
Yeah.. we are cutting "org.whatever" away for the OSD so it doesn't get too long. That was implemented long before we even had the window rule framework. Maybe we could make the behavior configurable, thoughts @johanmalm ?

The only way to get the correct app_id currently is via a foreign toplevel client like waybar or by looking into the labwc logs (might additionally require starting labwc with `--verbose` or `--debug`, not sure right now what log level that specific message uses).

**Comment by stefonarch** [comment]
I always forget the name  but `lswt` does show app_id well too.

**Comment by kyak** [comment]
Both `lswt` and `wlrctl toplevel list` reveal the application id; thank you!

As for the long name, we can get the idea from `waybar-wlr-taskbar`: https://man.archlinux.org/man/waybar-wlr-taskbar.5.en

They provide a `rewrite` rule which allows user to replace anything they want from the formatted string.

I use it like this to display better names:

```
   "wlr/taskbar": {
      "on-click": "minimize-raise",
      "format": "{icon}{app_id}",
      "rewrite": {
        "org.telegram.desktop": "Telegram",
        "firefox": "Firefox",
        "thunderbird": "Thunderbird",
      },
    },
```

**Comment by johanmalm** [comment]
Yes, we ought to make this configurable.

And we ought to address the inconsistency. Suggest the removal of org.foo. should be a customisation and "identifier" should do what it says on the tin (e.g. org.Foo.bar rather than bar)

**Comment by stefonarch** [comment]
Thanks @kyak , with your example I managed to find the issue why `rewrite` did never work here.
I had
```
    "wlr/taskbar": {
        "format": "{icon} {name}",
        "icon-size": 32,
        "tooltip-format": "{title}",
        "rewrite": {
                     "Firefox Browser Web":"Firefox",

...
```
The space between icon and name was the culprit. Did i in the .css file now. End of OT ;)

**Comment by xxhh1112** [comment]
qq

**Comment by kyak** [comment]
> Yes, we ought to make this configurable.
> 
> And we ought to address the inconsistency. Suggest the removal of org.foo. should be a customisation and "identifier" should do what it says on the tin (e.g. org.Foo.bar rather than bar)

I'll be looking into it in the next days.

@johanmalm @Consolatis any additional thoughts/ideas before I get to it?

**Comment by Consolatis** [comment]
Not really, the only question for me is what we want as the default. My vote would be for the cut-off variant as what we have now to not surprise users and also keep the `OSD` easier to read. I'd think the percentage of people using window rules is also pretty low (maybe not in the group of users that are using the master branch though).

**Comment by johanmalm** [comment]
@kyak I think what we really want to show in the window-switcher OSD is not the identifier (e.g. org.Foo.bar) but the `Name` of the application as specified in `/usr/share/applications/<identifier>.desktop` (and other `$XDG_DATA_DIRS`)

I think this would be a really interesting thing to implement, but it's probably not trivial.
I think it would basically involved the following:
- Iterate over `$XDG_DATA_DIRS` (colon separated paths) and `$XDG_DATA_HOME` to parse all `.desktop` files and produce a list (or vector/hashmap) of  identifiers and their respective `Name`.
- Update the list when needed (either check for change before it's called - or use inotify or similar to update on change). I suspect the easiest approach is to record the latest modified-time (using `stat()` and `st_mtime`) of the directories containing .desktop files and then check for change every time we call data. I think the parsing would be so quick that you wouldn't notice it - and changes are likely to be infrequent.

There are libraries that perform this type of stuff, but I think it'd be more attractive in the long run to just implement it and avoid dependencies belonging to particular eco-systems that we're not otherwise part of.

**Comment by Consolatis** [comment]
I think that will get messy pretty fast.
Maybe something for the future to consider but currently I think the cut-off identifier is fine.

**Comment by johanmalm** [comment]
Yes, okay.
