### ISSUE TITLE
Xwayland application loose focus

### ISSUE THREAD

**Issue by kyak** [labwc/labwc#1130]
Something's wrong when trying to focus Xwayland apps.

For example, run xeyes. Then switch to another window. Then try to switch back to xeyes.

First of all, xeyes is not even in the Alt+Tab list. Secondly, it is shown in waybar's taskbar, but clicking it doesn't raise the window, nothing happens.

**Comment by Consolatis** [comment]
I wonder if its fallout from
- #1103

Thoughts @jlindgren90 ?

Maybe xeyes doesn't actually want focus in the first place, does it happen with other X11 applications as well?

**Comment by kyak** [comment]
It happens with other X11 applications as well.

xeyes is just an example.

**Comment by jlindgren90** [comment]
This is the correct behavior for xeyes. It's a "passive" application and can't receive input focus. It doesn't show up in Alt-Tab under Openbox either.

It would be interesting to know which "other X11 applications" behave the same way.

**Comment by kyak** [comment]
> It would be interesting to know which "other X11 applications" behave the same way.

MATLAB.

I need to mention that it worked before.

**Comment by jlindgren90** [comment]
For xeyes, I do notice Openbox still raises the window (but doesn't give focus - title bar remains inactive) when clicking on it from the taskbar. Maybe we should do the same.

**Comment by stefonarch** [comment]
The only xwayland app here is element-desktop and it works as ever.

**Comment by kyak** [comment]
> is MATLAB focusable under Openbox? Can you share the output of `xprop` for the MATLAB window?

Yes, it's focusable and appears in Alt-Tab. Just as it was in labwc until recently. Here's the output of xprop: https://dpaste.com/BN2KPHZVH

> For xeyes, I do notice Openbox still raises the window (but doesn't give focus - title bar remains inactive) when clicking on it from the taskbar. Maybe we should do the same.

If you do the same as Openbox does, there will be a problem described in this bug report: https://www.mathworks.com/support/bugreports/1797911 ("Text fields in a MATLABWindow application on some Linux desktop environments do not allow text entry"). I had a workaround in place for Openbox described here: https://wiki.archlinux.org/title/MATLAB#Unable_to_type_in_text_fields_of_interfaces_based_on_MATLABWindow. Other workarounds include switching to other desktop environments like XFCE.

I'm in favor of the previous behaviour of labwc. It was great that focusing into text fields just worked.

**Comment by jlindgren90** [comment]
I need to think about this more, and maybe study how wlroots is doing things. The X11 focus model is complicated and it seems tricky to map to Wayland correctly.

**Comment by jlindgren90** [comment]
Is there any application (that's meant to receive keyboard input - not xeyes) other than MATLAB that has this issue? I'd like to debug it a bit but don't really want to sign up for a MATLAB trial.

**Comment by Consolatis** [comment]
> https://www.mathworks.com/support/bugreports/1797911
>> To view bug reports, sign in to your MathWorks Account or create a new one.

From Arch wiki:
> Since R2018a, it is not possible to type text in interfaces based on MATLABWindow - like Signal Editor, Add-Ons Explorer and others. MATLABWindow and MATLAB's webwindow infrastructure is based on Chromium Embedded Framework, and it looks like a known and long standing bug: https://bitbucket.org/chromiumembedded/cef/issues/2026/multiple-major-keyboard-focus-issues-on
>> Log in to continue

Seriously? What the heck.

Anyway, the arch wiki makes it sound like an issue with CEF so maybe other applications using CEF have the same issue.
Alternative approach: maybe CEF also supports running under wayland native?

**Comment by jlindgren90** [comment]
Thanks @Consolatis. From https://github.com/tiliado/cef/commit/2f5cc2ab3b99a3114388969929c8e1ef8fd9825d it looks like CEF is doing some funky stuff with `XSetInputFocus()` calls. In other words it's trying to control the keyboard focus itself rather than allowing the window manager to do it. (One of the lovely "legacy" features of X11.)

At this point, I know more than I ever wanted to know about the X11 focus model, and I still don't know how we could perfectly simulate it in the Wayland world. We don't want to allow any old `XSetInputFocus()` call to steal focus; that was an issue that X11 window managers struggled with before Wayland ever existed. But obviously leaving any application (even a proprietary one) unusable when it used to work is not great either.

As a compromise, my suggestion is to revert cae96b0cce441dd9f1981c312ae0108b3b4e42c9 but leave the other commits from #1103 in place. This would make it possible again to focus views with `WM_HINTS.input = false` by clicking on them (or on their taskbar button, if they have one). So it would hopefully make MATLAB usable again. Those views would still not be listed in Alt-Tab and would not be considered by automatically focused if another view on top was closed/minimized/etc.

I expect that will not make anyone (including myself) 100% happy, but I can't think of anything better at this point. I'll create a pull request and we can discuss details further there if needed.

**Comment by jlindgren90** [comment]
@kyak Please test #1137 and let us know it it helps at least somewhat.

**Comment by kyak** [comment]
> @kyak Please test #1137 and let us know it it helps at least somewhat.

Thanks, I'll give it a try! Just need some time.
