### ISSUE TITLE
Fullscreen window hides Waybar on all workspaces

### ISSUE THREAD

**Issue by tsujan** [labwc/labwc#1158]
The first time I encountered this problem, I thought Waybar had crashed: Skype's window was fullscreen, and I changed the workspace by pressing a `GoToDesktop` shortcut, but there was no trace of Waybar anywhere. However, as soon as I unfullscreened Skype, Waybar was shown on all workspaces.

Then I saw the same thing happened when I fullscreened FeatherPad (Qt6), Falkon (Qt5), Firefox or any other window. Apparently, the toolkit wasn't relevant.

I don't know whether this behavior is specific to Waybar or it happens with other panels too; hence the title of this report.

I use 0.6.5, the latest release for now.

EDIT: I have no window rule for Waybar in `rc.xml`.

**Comment by Consolatis** [comment]
This is caused by us being lazy and not resetting the "top" layer when switching workspaces.
That one is a bit special as we hide it whenever we go into fullscreen, but obviously we should show it again when we are leaving the workspace with the active fullscreen window.

In the meantime you can configure waybar to use the "bottom" layer (+ exclusive zone if not already using that).
That should make stuff work, regardless of fullscreen windows.

**Comment by heroin-moose** [comment]
Was too lazy to report, thank you.

**Comment by Consolatis** [comment]
Should be fixed in latest master. Feel free to comment if there are further issues with top layer layershell surfaces and fullscreen.

**Comment by tsujan** [comment]
Thanks!

I'll wait for 0.6.6 to have recent fixes and changes (0.6.5 has been rock solid here).

**Comment by johanmalm** [comment]
> Thanks!
> 
> I'll wait for 0.6.6 to have recent fixes and changes (0.6.5 has been rock solid here).

Will have a three week cool down period. Aiming for release 2-Dec.
