### ISSUE TITLE
All keybindings are gone after pressing weird key combos

### ISSUE THREAD

**Issue by kyak** [labwc/labwc#1200]
It looks like `Alt+Shift+Caps` breaks all keybindings reliably. They simply don't work any more.

To restore from this situation, I can press `Alt+Shift+Caps+a`.

**Comment by Consolatis** [comment]
My first thought was that we are only checking the `translated` keysyms for modifiers (e.g. those that apply existing modifiers to the pressed key) and we should use the `raw` keysyms instead (without existing modifiers applied). After testing that theory it turned out that it doesn't make a difference. I don't know when I am able to properly debug this so further eyes on the issue would be appreciated.

**Comment by stefonarch** [comment]
Can't reproduce here, but looks similar to like https://github.com/labwc/labwc/issues/1129

**Comment by Consolatis** [comment]
> Can't reproduce here, but looks similar to like #1129

Indeed, I strongly assume that it is the same root cause: we add something to the "pressed" set of keys but don't receive a release event and thus its stuck in the set and all following keybind fail because of that.

**Comment by kyak** [comment]
It seems that `Shift+Caps` is enough to make keybinds stuck.

I need to mention that `Caps` is used here for keyboard layout switching.
