### ISSUE TITLE
wlroots version

### ISSUE THREAD

**Issue by johanmalm** [labwc/labwc#121]
It looks like the next version of wlroots will come out soon (https://emersion.fr/blog/2021/status-update-35/)

I'm thinking of setting the required version in meson.build to the new tag (0.15.0 or whatever) rather than tracking the master.

I think it'll be easier for maintainers that way, and it lets us do smaller releases more often without creating a dependency mess.

Any thoughts? Particularly @ARDiDo and @Joshua-Ashton 

If wlroots keeps having lots of breaking changes with could track the master in the separate branch.

**Comment by droc12345** [comment]
My opinion, set a version for wlroots, it changes often enough to specify it for a certain set of features.

**Comment by ARDiDo** [comment]
It might be a good idea to base labwc off of the next stable release, so it would be more compatible with distros that use the stable version. Creating a separate branch to track wlroots-master may make bringing the 'stable' branch up to date easier when there is a new wlroots version.

**Comment by johanmalm** [comment]
> It might be a good idea to base labwc off of the next stable release, so it would be more compatible with distros that use the stable version. Creating a separate branch to track wlroots-master may make bringing the 'stable' branch up to date easier when there is a new wlroots version.

Yes, that’s exactly what I’m thinking :smile:
It would involve a small amount of extra dev work, but enables smaller releases when it suits us rather than waiting for wlroots.

I can understand why sway operate the way they do, but we’re just much earlier in the project life-cycle.

**Comment by johanmalm** [comment]
@ARDiDo 
Looks like wlroots 0.15.0 is out.
Suggest we now set =0.15.0 in meson.build and point `subprojects/wlroots.wrap` to that particular revision.
Just wanted to check you agree.
I'll start updating `NEWS.md` in readiness for `0.4.0`. No rush because I don't suspect distros will upversion until sway does.

**Comment by jbeich** [comment]
> Suggest we now set =0.15.0

wlroots may have 0.15.1 which should be API/ABI compatible.

> I don't suspect distros will upversion until sway does.

[FreeBSD already did](https://github.com/freebsd/freebsd-ports/commit/2af7805da5c5fc73eb28fba4065cead63c4bb5ab). ;) wlroots upstream actually [recommends bundling](https://gitlab.freedesktop.org/wlroots/wlroots/-/wikis/Packaging-recommendations) (via `--default-library=static`) due to unstable API.

**Comment by droc12345** [comment]
Add a constraint to meson.build like this (you can leave off the required get option part) 

wlroots        = dependency('wlroots', version: ['>=0.15.0', '<0.16.0'], required: get_option('use_system_wlroots'))

The way this is writtten it will try and use wlroots (installed) if version 15 and use it's (packaged) version otherwise.

**Comment by johanmalm** [comment]
@Narrat do you have a view?

**Comment by ARDiDo** [comment]
@johanmalm, I think I like the way that @droc12345, formatted the meson.build dependency. 
I agree that we should wait until sway, and distros, start using 0.15.0 before we update anything.
Earlier, I bumped the wlroots dependency to the latest in the master branch, and bringing it down to 0.15.0 would break compatibility with both the master branch and with most distros.

**Comment by Narrat** [comment]
I can only say what I wish for. And the most important wish would be kinda support for pointed releases. On the AUR page for `labwc` was a question if some patches could be applied. But as all of you added and fixed a lot of stuff since the last release, this was an impossible task for me :D
How this can be achieved really depends on how you want to move on. In that regard I really like the idea mentioned by ARDiDo.
In pinning master to the wlroots range suggested by droc12345, create a devel branch, which follows and adapts the breaking changes and needs to be rebased from time to time with said master. If there is a new wlroots release, this branch could be merged and the new cycle begins. Would allow for more frequent releases independent from wlroots. Not to much hassle in keeping track of things. And the `labwc-git` PKGBUILD can easily be adjusted to using such a branch.

Regarding the waiting: Well, dunno how much time there is. Arch already has a [todo-list](https://archlinux.org/todo/new-wlroots-release-is-in-community-staging-please-check-your-packages-and-push-a-rebuild-or-a-new-version-when-available-thanks/). So it only depends on how fast the mentioned packages are updated (either because they work out of the box, or issued new releases).

**Comment by droc12345** [comment]
The wrap for wlroots I investigated to see what it needs (I was wrong above)
url = https://gitlab.freedesktop.org/wlroots/wlroots <== this is fine
revision = master <== master would change to 0.15.0 for wlroots version 15, which equates to one of the tag levels.
instead of a tag, a commit id could be used, to shut off at a certain level.

In looking at the main meson files, I didn't like the logic for deciding wlroots, it didn't work in some case (for me)
so I rewrote the meson.build (part of it) and added a system-wlroots flag to meson_options to help with making decisions.
it's at https://github.com/droc12345/labwc/tree/alpha if you want to look at it.

**Comment by johanmalm** [comment]
Thanks all for helping with this.

I think there are two main options:

Option A - set `labwc` master branch `wlroots.wrap` and `meson.build` to the latest `wlroots` tag (0.15.0 in this case).

Option B - track `wlroots` master branch and just create new `labwc` branches for each `labwc` release (for which we then set `wlroots.wrap` and `meson.build`)

In thinking this through it's worth considering that:

- There have been breaking changes between each of the recent wlroots minor releases; generally quite a few.

- `sway` is pretty stable and has been declared feature complete, so the devs are mostly looking at bug fixes, code simplification and stability. `sway` uses something similar to Option B.

- `hikari`, `cage` and `dwl` are close to Option A where their respective master/main branches depend on tagged `wlroots` releases. Some have a separate branch that handles wlroots-master breaking changes, but I think I'm right in saying that they don't merge/rebase these until the next wlroots release.

I prefer option A for the following reasons:

(a) It enables us to make labwc releases whenever we want against the latest wlroots release. It was 6 months between wlroots `0.14.0` and `0.15.0` which is longer than I think we wanted to wait really.

(b) `labwc` is at different stage in its life-cycle (earlier) compared with `sway` and I think it's important for us to be able to do releases at more regular intervals than wlroots is likely to.

(c) It avoids breaking the `labwc` master branch just because `wlroots` have introduced another breaking change. Whilst it's normally quick to fix, it has often taken us a day or two to discover and action.

I think the main disadvantage is that the `wlroots` master might receive a fix a new feature that we want - for example relating to `wlr_scene()`. Suggest we cross that bridge when we come to it.

If I was a distro I'd consider statically link wlroots compositors, to avoid all this dependency stuff, but it's really up to them :smile:

**Comment by droc12345** [comment]
I concur and think the A option is good, that gives you a stable base.

If (big if) there are fixes that won't affect building the version as it is, I think would be fine to add to a tagged version.
But any big change additions like wlr_scene I would target for the next release, that gives everyone time to get it right.

**Comment by johanmalm** [comment]
I've pushed a commit to make it so.
