### ISSUE TITLE
Fullscreen windows are un-fullscreened when monitor is turned off

### ISSUE THREAD

**Issue by vanfanel** [labwc/labwc#1560]
Hi there,

I have noticed that, with labwc only (Sway or Weston don't seem to do it), when I turn off the display, any focused fullscreen window is transformed by labwc into a non-fullscreen window.

It's very simple to reproduce:
-Open a fullscreen window (like RetroArch, or an SDL2 game, etc)
-Turn off the monitor, then turn it on again.
-See how the fullscreen window is now a normal window.

Since only Labwc seems to do it, I believe this is clearly a bug, right?

**Comment by ahesford** [comment]
It's not so much a bug as a design decision, but maybe the logic needs refinement if we lose the only connected display. Are you seeing this behavior with a single display, or do you have multiple heads?

When you turn off your display and turn it back on again, your monitor or graphics adapter is generating a disconnect/reconnect event. It seems that AMD hardware is very aggressive about this, while Intel is not always aggressive enough. What frustrates me is that the AMD driver doesn't fire the disconnect/reconnect sequence until after the display is powered back on. It would be better to send the disconnect as soon as the display goes off and send the reconnect when it comes back on, to better reflect actual display usability. However, I don't know if or where that behavior might be changed.

In a multiple-display setup, all client views are evacuated from a display that is disconnected and moved onto the nearest available display. (These views store their last position before evacuation, so they will be restored to their original location when the display returns.) However, we un-maximize windows before evacuation.

In general, we interpret a "disconnect" as an intentional reconfiguring of the output. Imagine you have a small display connected beside your primary laptop output and, because it's small, you use it with a maximized mail client and nothing else. At some point, you disconnect that small display and connect the laptop to a nice 4k TV. In the process, our evacuation/restoration behavior will 1) yank your mail client onto the primary display when you pull the plug, un-maximizing it in the process; 2) determine after the TV is connected that the mail client's original location can be restored, so the view will be relocated to the TV. It is not clear in either of these stages that preserving the maximized status is desirable.

That is not generally true for a "power-down" event caused by, for example, `wlopm`. We intentionally do *not* reconfigure the output when the display goes dark without a hardware disconnect, because we assume the display will eventually wake up again and your views should be preserved. Unfortunately, in your case, the hardware triggers the disconnect and we are unable to tell the difference between you sleeping a display or yanking its cable.

**Comment by vanfanel** [comment]
> It's not so much a bug as a design decision, but maybe the logic needs refinement if we lose the only connected display. Are you seeing this behavior with a single display, or do you have multiple heads?

Single display.

**Comment by charbelnicolas** [comment]
I have this rule for all windows:

`<windowRule identifier="*" serverDecoration="no" fixedPosition="yes" />`

When I turn the monitor off and back on, the foot terminal fullscreen window unmaximizes itself and adds the server decorations even though I have the `windowRule` `serverDecoration` set to `no`.

Should I open a new issue for this?

**Comment by johanmalm** [comment]
> Should I open a new issue for this?


Yes please. I'm not sure what's going on there. It might be a issue relating to when we apply the window-rules.

**Comment by vanfanel** [comment]
Fixed via https://github.com/labwc/labwc/commit/0f6d5cc26a9d76954f995b82addfd5e9aac963b9

Many, many thanks to @jlindgren90 for this! :)
