### ISSUE TITLE
Alt-tab does not change which window gets scroll events

### ISSUE THREAD

**Issue by bi4k8** [labwc/labwc#162]
This is a surprising one, but probably there's just some kind of focus setting missing in the alt-tab code.

To reproduce:
1. open two windows that overlap but where neither is contained by the other
2. put the cursor in the overlap region; notice that scrolling goes to the window on top
3. without moving the cursor, hit alt-tab to switch which window is on top and then scroll again
4. notice that the window now in the back (without keyboard focus) scrolls instead of the newly-focused, raised window

Moving the cursor even a single pixel makes subsequent scroll events go to the newly-focused, raised window as expected.

**Comment by johanmalm** [comment]
Fixed by 6651d45ed44e2af

**Comment by Consolatis** [comment]
This bug will never end I guess: after 6651d45ed44e2af28e8f99f326cb4ef4190f0bdd has been reverted because of side effects ([caused fake `MOUSE_ACTION_DRAG`](https://github.com/labwc/labwc/issues/193#issuecomment-1019163749) + #210) and 8dd3dc3e3bcbab2b0b8a0c1432d1a8ef7a7f6a6a was done to replace it, that one now actually appears to cause #225. When i remove `cursor_rebase()`, touchpad scrolling works without crashing qutebrowser.

We may need to come up with another solution.
