### ISSUE TITLE
Feature request: dynamic SnapToEdge sizing

### ISSUE THREAD

**Issue by Vladimir-csp** [labwc/labwc#1799]
Idea: resizing window in snapped-to-edge state does not make it drop snapped state, but instead resizes current workspace's two edge snap regions: current and the opposite.

**Comment by Consolatis** [comment]
This goes quite a bit into the "tiled window manager" direction. The issue I see with this is that it would only work for 2 windows per direction. It is also not clear how this would work if you have multiple stacked windows on top of each other that are all snapped to the same output edge.

**Comment by tsujan** [comment]
Describing my opposite point of view:

When the feature requested here was implemented in KWin (recently), it was annoying to me because I relied on the window size after snapping, and the only way to restore it was logging out and in and avoiding resizing of snapped windows (which I did a lot before).

**Comment by Vladimir-csp** [comment]
> This goes quite a bit into the "tiled window manager" direction. The issue I see with this is that it would only work for 2 windows per direction. It is also not clear how this would work if you have multiple stacked windows on top of each other that are all snapped to the same output edge.

Perhaps it would set size for two snapped regions on workspace (left+right edge or top+bottom edge), so any window that is snapped to that edges on workspace would be affected.

> the only way to restore it was logging out and in

An action to restore horizontal or vertical edge snap border position?

**Comment by tsujan** [comment]
> An action to restore horizontal or vertical edge snap border position?

Possible.

But, frankly, I'm getting a little worried. LabWC is very stable and lightweight. For keeping it so,  adding of new futures may need to be limited to the most useful or popular ones. Not setting a limit for new features might result in a chaos.

Of course, I'm not a developer of LabWC — I'm only a user of it — but I said that based on my experience as a developer in in other places.

**Comment by Consolatis** [comment]
> For keeping it so, adding of new futures may need to be limited to the most useful or popular ones. Not setting a limit for new features might result in a chaos.

That sums it up pretty good. I'd add to that that some features can be provided in a way that allow for multiple usage patterns but  others simply can not be provided this way or introduce massive complexity in the code base which makes it harder to maintain / enhance in the future.

Then there is also the user expectation aspect, if we were to implement something like requested here users may then end up choosing labwc for this feature because it fits their expectations but related expectations are not fulfilled (e.g. more than 2 windows in each direction, separate sizes per workspace, a set of "layouts" which can be cycled through, "dynamic tiling" and so on).

At the current point I'd say that labwc adding this feature is unlikely.

**Comment by johanmalm** [comment]
This is out of scope.

Can be done with regions and a client. I did some prototyping a while ago: https://github.com/johanmalm/labwc-regions

**Comment by Teascade** [comment]
@johanmalm Can you elaborate on how this can be done? I don't mind if I would have to use external tools, but ie. tiling two windows side-by-side and then resizing the other to resize them both is certainly a very good feature that I used a lot back when I used Windows 10. It's been 5 years since my move to Linux, and I still miss that feature.

I do for the most part like stacking window managers more than tiled ones, so labwc is in this regard easily the best choice for me, but right now the best way for me to accomplish "slightly off-center tiling" is to either 1. tile the windows left and right, manually resize and hope it's even possible (some programs refuse being resized after being tiled), and then resize both windows individually. Works, but tedious. 2. Simply resize both windows correctly from the get-go. Also works, but even more tedious.

Evidently it's possible, as you've attempted it, but the linked prototyping repository with no readme isn't exactly .. the most accessible way of sharing how.

**Comment by Consolatis** [comment]
If you just want something static like 1/3 on the left and 2/3 on the right you can do so using [regions](https://labwc.github.io/labwc-config.5.html#regions). You can also define overlapping regions (e.g. 25% left 75% right + 34% left 66% right and so on) and then use either keybinds / mouse triggered menus or mouse + modifier to see previews.

Those are not dynamic though, so snapping one window will not effect others.

**Comment by Teascade** [comment]
> If you just want something static like 1/3 on the left and 2/3 on the right you can do so using [regions](https://labwc.github.io/labwc-config.5.html#regions). You can also define overlapping regions (e.g. 25% left 75% right + 34% left 66% right and so on) and then use either keybinds / mouse triggered menus or mouse + modifier to see previews.
> 
> Those are not dynamic though, so snapping one window will not effect others.

Yes that would be the problem. The size of the regions that I want and need depend and vary much on the software that I want to tile, so static regions won't work for me.

**Comment by johanmalm** [comment]
I use MS Windows daily too and know the feature well. `labwc` does not currently support this and I don't think it's trivial to implement. I also think complexity would increase more than proportionately with lines-of-code.

It might be easier to discuss such a feature though if someone wants to draft a patch.

The regions client mentioned above draws currently configured regions and allows interactive resize. It's not exactly like the MS Windows feature, in that it only allows resizing of one region at a time, but it was just quick/dirty idea. I don't suspect it would be that hard to change to resize multiple. It would require a `--reconfigure` though, and although you get a visual representation in the layer-shell overlay layer, the actual window do not resize until the `--reconfigure`. Just build it with `meson setup build && ninja -C build` if you want to explore further.

I personally use `MoveToEdge`, `GrowToEdge`, and `ShrinkToEdge` at the moment. It's a different workflow, but I find it more flexible.

```XML
    <keybind key="W-Left">
      <action name="MoveToEdge" direction="left" snapWindows="true"/>
    </keybind>
    <keybind key="W-Right">
      <action name="MoveToEdge" direction="right" snapWindows="true"/>
    </keybind>
    <keybind key="W-Up">
      <action name="MoveToEdge" direction="up" snapWindows="true"/>
    </keybind>
    <keybind key="W-Down">
      <action name="MoveToEdge" direction="down" snapWindows="true"/>
    </keybind>
    <keybind key="W-S-Left">
      <action name="ShrinkToEdge" direction="left"/>
    </keybind>
    <keybind key="W-S-Right">
      <action name="GrowToEdge" direction="right"/>
    </keybind>
    <keybind key="W-S-Up">
      <action name="ShrinkToEdge" direction="up"/>
    </keybind>
    <keybind key="W-S-Down">
      <action name="GrowToEdge" direction="down"/>
    </keybind>
```

**Comment by Teascade** [comment]
> I use MS Windows daily too and know the feature well. `labwc` does not currently support this and I don't think it's trivial to implement. I also think complexity would increase more than proportionately with lines-of-code.
> 
> It might be easier to discuss such a feature though if someone wants to draft a patch.
> 
> The regions client mentioned above draws currently configured regions and allows interactive resize. It's not exactly like the MS Windows feature, in that it only allows resizing of one region at a time, but it was just quick/dirty idea. I don't suspect it would be that hard to change to resize multiple. It would require a `--reconfigure` though, and although you get a visual representation in the layer-shell overlay layer, the actual window do not resize until the `--reconfigure`. Just build it with `meson setup build && ninja -C build` if you want to explore further.
> 
> I personally use `MoveToEdge`, `GrowToEdge`, and `ShrinkToEdge` at the moment. It's a different workflow, but I find it more flexible.
> 
> ```
>     <keybind key="W-Left">
>       <action name="MoveToEdge" direction="left" snapWindows="true"/>
>     </keybind>
>     <keybind key="W-Right">
>       <action name="MoveToEdge" direction="right" snapWindows="true"/>
>     </keybind>
>     <keybind key="W-Up">
>       <action name="MoveToEdge" direction="up" snapWindows="true"/>
>     </keybind>
>     <keybind key="W-Down">
>       <action name="MoveToEdge" direction="down" snapWindows="true"/>
>     </keybind>
>     <keybind key="W-S-Left">
>       <action name="ShrinkToEdge" direction="left"/>
>     </keybind>
>     <keybind key="W-S-Right">
>       <action name="GrowToEdge" direction="right"/>
>     </keybind>
>     <keybind key="W-S-Up">
>       <action name="ShrinkToEdge" direction="up"/>
>     </keybind>
>     <keybind key="W-S-Down">
>       <action name="GrowToEdge" direction="down"/>
>     </keybind>
> ```

Thanks for the suggestion! I tried it, and it is for sure an interesting workflow, and I'm almost tempted to try it long-term. The issue I find with it is that it doesn't use actual "tiling" like regions do; so windows can simply "decide" not to fit into smaller areas, where regions can force the windows smaller, which can be quite handy sometimes.

This has given me some ideas though that I will probably try, but let it not go unspoken that it would be very nice to have _some_ way of editing regions dynamically (or in other words, without changing rc.xml and running reconfigure.
