### ISSUE TITLE
[Bug][Commit bisected] Commit breaks fullscreen SDL2 programs behaviour

### ISSUE THREAD

**Issue by vanfanel** [labwc/labwc#1812]
Hi there,

This commit:
https://github.com/labwc/labwc/commit/bd5dcb34855a02e465ed39af67eaa7a601558dc8
breaks certain SDL2 games fullscreen startup: when they are started in fullscreen mode, they fail to run in fullscreen mode, being displayed on a window instead.
Before this commit, they started nicely in fullscreen mode when told to do so.

I have found these games are affected by this commit (probably most of the programs and games are affected):
-OpenTyrian (https://github.com/opentyrian/opentyrian), configure it to start in fullscreen mode inside the game menu, then re-run the game.
-Schismtracker (https://github.com/schismtracker/schismtracker), start with `schismtracker -f`
-sm64ex-alo (https://github.com/AloUltraExt/sm64ex-alo), configure it to start in fullscreen mode inside the game menu, then re-run the game.

Before this commit, the games started nicely in fullscreen mode when configured or told to do so.

NOTES:
-Other WLRoots-based compositors are not affected. Current Sway for example runs the fullscreen SDL2 programs nicely.
-Weston compositor is not affected.

**Comment by tokyo4j** [comment]
I did some debugging with OpenTyrian and found that the geometry of `wl_surface` committed by the client is windowed, even though the geometry of `xdg_surface` is fullscreen. I guess we are requesting back the geometry of `wl_surface` to the client, so the client keeps drawing in the windowed geometry even though it's actually fullscreen. I don't know if this is our bug or SDL2's bug as I'm missing the context of https://github.com/labwc/labwc/commit/bd5dcb34855a02e465ed39af67eaa7a601558dc8.

Here's the debug log with some `wlr_log()`s:

patch:
```diff
diff --git a/src/xdg.c b/src/xdg.c
index 488f67fd..35dcff47 100644
--- a/src/xdg.c
+++ b/src/xdg.c
@@ -152,6 +152,14 @@ handle_commit(struct wl_listener *listener, void *data)
 
 	if (update_required) {
 		view_impl_apply_geometry(view, size.width, size.height);
+		wlr_log(WLR_ERROR, "applied geometry: %dx%d", size.width, size.height);
+		wlr_log(WLR_ERROR, "wl_surface geometry: %dx%d",
+			xdg_surface->surface->current.width, xdg_surface->surface->current.width);
+		wlr_log(WLR_ERROR, "xdg_surface geometry: %dx%d",
+			xdg_surface->current.geometry.width, xdg_surface->current.geometry.height);
+		struct wlr_box box;
+		wlr_xdg_surface_get_geometry(xdg_surface, &box);
+		wlr_log(WLR_ERROR, "computed xdg_surface geometry: %dx%d", box.width, box.height);
 
 		/*
 		 * Some views (e.g., terminals that scale as multiples of rows
```

```
[1638640.969] xdg_toplevel@36.set_fullscreen(wl_output@22)
[1638641.054] wl_display@1.sync(new id wl_callback@37)
[1638641.058]  -> wl_callback@37.done(48)
[1638641.061]  -> wl_display@1.delete_id(37)
[1638641.064]  -> xdg_toplevel@36.configure(1280, 720, array[4])
[1638641.067]  -> xdg_surface@35.configure(48)
[1638642.070] wl_surface@29.set_buffer_scale(1)
[1638642.092] xdg_surface@35.set_window_geometry(0, 0, 1280, 720)
[1638642.097] wl_compositor@6.create_region(new id wl_region@37)
[1638642.102] wl_region@37.add(0, 0, 1280, 720)
[1638642.106] wl_surface@29.set_opaque_region(wl_region@37)
[1638642.109] wl_region@37.destroy()
[1638642.112]  -> wl_display@1.delete_id(37)
[1638642.115] xdg_surface@35.ack_configure(48)
[1638642.120] zwp_linux_dmabuf_v1@28.create_params(new id zwp_linux_buffer_params_v1@38)
[1638642.124] zwp_linux_buffer_params_v1@38.add(fd 58, 0, 0, 2560, 16777216, 8)
[1638642.128] zwp_linux_buffer_params_v1@38.add(fd 65, 1, 1064960, 320, 16777216, 8)
[1638642.131] zwp_linux_buffer_params_v1@38.add(fd 66, 2, 1073152, 64, 16777216, 8)
[1638642.134] zwp_linux_buffer_params_v1@38.create_immed(new id wl_buffer@39, 640, 400, 875713112, 0)
[1638642.149] zwp_linux_buffer_params_v1@38.destroy()
[1638642.152]  -> wl_display@1.delete_id(38)
[1638642.155] wl_surface@29.attach(wl_buffer@39, 0, 0)
[1638642.160] wl_surface@29.damage(0, 0, 2147483647, 2147483647)
[1638642.163] wl_surface@29.commit()
[1638642.237]  -> wl_keyboard@33.leave(49, wl_surface@32)
[1638642.243]  -> wl_keyboard@18.leave(49, wl_surface@32)
[1638642.246]  -> wl_keyboard@25.enter(50, wl_surface@29, array[4])
[1638642.249]  -> wl_keyboard@25.modifiers(51, 0, 0, 16, 0)
[1638642.262]  -> wl_data_device@11.selection(nil)
[1638642.315]  -> zwp_primary_selection_device_v1@12.selection(nil)
[1638642.333]  -> wl_surface@29.enter(wl_output@22)
00:00:05.571 [ERROR] [../src/xdg.c:155] applied geometry: 640x400
00:00:05.571 [ERROR] [../src/xdg.c:156] wl_surface geometry: 640x640
00:00:05.571 [ERROR] [../src/xdg.c:158] xdg_surface geometry: 1280x720
00:00:05.571 [ERROR] [../src/xdg.c:162] computed xdg_surface geometry: 640x400
```

**Comment by droc12345** [comment]
After the call to wlr_xdg_surface_get_geometry, sway adds a couple more checks than what labwc does
``    bool new_size = new_geo.width != view->geometry.width ||``
``            new_geo.height != view->geometry.height ||``
``            new_geo.x != view->geometry.x ||``
``            new_geo.y != view->geometry.y;``

where labwc only checks for width/height not sure if that makes a difference in this case.

Sway - sway/desktop/xdg_shell.c ~ line 300
labwc - src/xdg.c ~ line 116

**Comment by Consolatis** [comment]
@ahesford, thoughts?

**Comment by ahesford** [comment]
I don't fully understand the problem, but it seems like the client lies about its size in the commit. If the value of `toplevel->scheduled.{width,height}` are zero when we force them to match `view->current` in the commit handler, a simple fix might be to avoid forcing `toplevel->scheduled` unless at least one of the values is nonzero.

This would override what wlroots thinks of the window dimensions only if it thinks something about the dimensions, in which case it would be forcing the geometry anyway.

**Comment by tokyo4j** [comment]
> If the value of `toplevel->scheduled.{width,height}` are zero when we force them to match view->current in the commit handler, a simple fix might be to avoid forcing toplevel->scheduled unless at least one of the values is nonzero.

The values of `toplevel->scheduled.{width,height}` are not zero when we send back the geometry that the client doesn't expect, because we call `wlr_xdg_toplevel_set_size()` with the fullscreen geometry when the client sends `xdg_toplevel.set_fullscreen` request.

The problem happens like this:
- Client sends `xdg_toplevel.set_fullscreen` request
- Labwc updates `toplevel->scheduled` with the fullscreen geometry, then sends `xdg_toplevel.configure` event with the fullscreen geometry.
- Client sends `wl_surface.commit` request with `xdg_surface` in the fullscreen geometry, but also with `wl_buffer` in the __windowed geometry__ for some reason.
- Labwc updates `toplevel->scheduled` with the windowed geometry returned by `wlr_xdg_surface_get_geometry()`, then sends `configure` event with the windowed geometry.

How about syncing `toplevel->scheduled` and `toplevel->current` like below?
I confirmed this fixes the problem.

```diff
diff --git a/src/xdg.c b/src/xdg.c
index 2b8bf96e..46bb8fa4 100644
--- a/src/xdg.c
+++ b/src/xdg.c
@@ -156,8 +156,8 @@ handle_commit(struct wl_listener *listener, void *data)
 			 */
 			struct wlr_xdg_toplevel *toplevel =
 				xdg_toplevel_from_view(view);
-			toplevel->scheduled.width = view->current.width;
-			toplevel->scheduled.height = view->current.height;
+			toplevel->scheduled.width = toplevel->current.width;
+			toplevel->scheduled.height = toplevel->current.height;
 		}
 	}
 }
```

**Comment by ahesford** [comment]
> How about syncing `toplevel->scheduled` and `toplevel->current` like below? I confirmed this fixes the problem. [...]

That change breaks the behavior that https://github.com/labwc/labwc/commit/bd5dcb34855a02e465ed39af67eaa7a601558dc8 was intended to fix:
1. Open a `foot` terminal (preferrably the newest version, 0.17.2)
2. Manually resize the foot window with a mouse, to some arbitrary size
3. Change the font size from the keyboard (by default, `Ctrl-+` or `Ctrl-<Hyphen>`); this will cause the `foot` window to resize itself to keep the same character grid with the larger or smaller font
4. Activate another window

With bd5dcb34 in place, nothing unexpected will happen. Reverting bd5dcb34 or replacing `view->current` with `toplevel->current` will cause `foot` to jump back to the window size that was set by step 2 as soon as the window is deactivated. Looking further, it seems that your proposal is a no-op anyway, because [wlroots should have already copied `toplevel->pending` into `toplevel->current`](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/0.17/types/xdg_shell/wlr_xdg_toplevel.c?ref_type=heads#L133) when handling the client commit.

I see no reason why the client should be committing a buffer with the windowed geometry, but if we want to work around seemingly broken clients, we'll have to get clever.

**Comment by Consolatis** [comment]
> [ 754288.319]  -> xdg_toplevel@38.configure(800, 600, array[0])

I don't understand the log above, where does that size come from?
The debug log seems to miss `view->current.width/height` (although it should be equal to `size`).

Maybe the issue here is actually the Qt-workaround above and `view->pending` is `0` and thus the extents match the new surface? However, there should be a debug message and I am not sure why modifying `toplevel->scheduled.height/width` would then fix that.

**Comment by ahesford** [comment]
If these clients behave as expected in Sway, I wonder if Sway handle the [foot resize issue](https://github.com/labwc/labwc/issues/1812#issuecomment-2122574915) properly if foot is floating rather than tiled (is this even possible?).

If not, it may be the case that we are correct, the client and Sway are both wrong, and two wrongs make a right here.

**Comment by ahesford** [comment]
> changing font size in latest foot on latest sway has foot resize correctly, then picking another window doesn't make it change size (stays the same). seems to behave correctly

Thanks for testing. Was the font change done after a manual resize of the window, or was foot still in its initially configured size? In labwc without the fix, foot will behave even after font resizing until a manual resize triggers `wlr_xdg_toplevel_set_size` and, through that, caching of the toplevel geometry.

**Comment by nekopsykose** [comment]
> Thanks for testing. Was the font change done after a manual resize of the window, or was foot still in its initially configured size? In labwc without the fix, foot will behave even after font resizing until a manual resize triggers wlr_xdg_toplevel_set_size and, through that, caching of the toplevel geometry.  

any order of operations i test seems to work ok and not have it resize itself to some older size inadvertantly

**Comment by tokyo4j** [comment]
To help debugging SDL2, I made a simple reproducer: 

```c
#include <SDL2/SDL.h>
#include <assert.h>

#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480

int main(int argc, char *args[]) {
    setenv("SDL_VIDEODRIVER", "wayland", 1);
    assert(SDL_Init(SDL_INIT_VIDEO) == 0);
    SDL_Window *window = SDL_CreateWindow("hello_sdl2", SDL_WINDOWPOS_UNDEFINED,
                                          SDL_WINDOWPOS_UNDEFINED, SCREEN_WIDTH,
                                          SCREEN_HEIGHT, SDL_WINDOW_HIDDEN);
    assert(window);
    SDL_Renderer *renderer = SDL_CreateRenderer(window, -1, 0);
    assert(renderer);
    SDL_SetWindowFullscreen(window, SDL_WINDOW_FULLSCREEN);
    SDL_ShowWindow(window);
    SDL_SetRenderDrawColor(renderer, 255, 0, 0, 255);
    SDL_RenderClear(renderer);
    SDL_RenderPresent(renderer);
    SDL_Delay(1000);
    SDL_DestroyWindow(window);
    SDL_Quit();
    return 0;
}
```

**Comment by vanfanel** [comment]
This is no more a bug with current SDL2 versions, it was fixed in SDL2 so no workarounds are needed:
https://github.com/libsdl-org/SDL/issues/11289 

@tokyo4j Thanks for your work  and investigation of this! :)
