### ISSUE TITLE
Window state combinations

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc#187]
What should happen if a view is in fullscreen and
- we toggle decorations
- we (un)maximize

In my opinion neither of those should do anything and thus labwc should check for view->fullscreen in their handlers and just return.
Are there valid usecases for allowing these mixed states that I am missing or are there other unwanted state combinations?

Fullscreen + Move could be valid to move a fullscreen application to another output, I didn't test that yet.

**Comment by ARDiDo** [comment]
Toggling decorations on a fullscreen window appears to just toggle it for when it isn't in fullscreen.
However, maximizing a fullscreen window makes the window have the dimensions as if it were maximized, making room for the window borders. However, the decorations still wont show show up.
We should either unfullscreen the window, or ignore the maximize request.
However, it may be better to wait until #185 is merged, since that makes big changes to the maximize and fullscreen functions.

**Comment by Consolatis** [comment]
I'd vote for ignoring all requests related to decorations and maximize while in fullscreen.

About fullscreen + Move I am still not sure about that.
I tried to test it using `WLR_X11_OUTPUTS=2 build/labwc -s foot` (in an X session) but there is something completely wrong with cursor coordinates and I hadn't had the time to debug whats going on there.

**Comment by johanmalm** [comment]
Yes, I support your vote on fullscreen handling

**Comment by Consolatis** [comment]
Alright, I'll send a PR tomorrow. If somebody else wants to tackle that before then: feel free :)

**Comment by ARDiDo** [comment]
I can take care of ignoring the requests. If you want @Consolatis, you can look into fullscreen + move.

**Comment by Consolatis** [comment]
Fullscreen + Move is for another time. Closing this for now as @ARDiDo fixed the more important cases.
