### ISSUE TITLE
Black dot instead of application icon

### ISSUE THREAD

**Issue by wastlnd** [labwc/labwc#1877]
I have noticed that when I open all the GTK app that I have (file manager, browser and so on) the window has a dot instead of the application tiny icon on top left. Icons are showing when I log with X server instead. This happens whatever the configuration labwc loads, also the default one. What could I do to at least narrow down the issue? TIA.

**Comment by johanmalm** [comment]
The black dot is just the built-in xbm icon.

We don't yet support SSD application icons because it's harder than it used to be on X11 (you have parse .desktop files against app_id and then parse icons themes, etc.)

With some toolkits (e.g. Gtk) you can get the application icon if you set `<core><decoration>client</decoration></core>`

With SSD you can:
1. Disable the menu icon with https://labwc.github.io/faq.html#server-side-decoration
2. Use a theme with a `menu.{xbm,png,svg}` for example https://github.com/labwc/labwc-artwork/tree/main/button-themes/svg/Adwaita/openbox-3

Will close with this, but please feel free to re-open if you have further questions/thoughts.
