### ISSUE TITLE
Waybar does not show language icon due to missing SWAYSOCK ipc functionality.

### ISSUE THREAD

**Issue by mkshevetskiy** [labwc/labwc#190]
Waybar subscribes to sway ipc input events and uses it do display language icon. This functionality is missing in labws, so no language icon is displayed.

with sway:

swaymsg -s /run/user/1000/sway-ipc.1000.2467960.sock -m -t subscribe '[ "input" ]'

when switch from english to russian the following input event occurs

{
  "change": "xkb_layout",
  "input": {
    "identifier": "0:0:X11_keyboard",
    "name": "X11 keyboard",
    "vendor": 0,
    "product": 0,
    "type": "keyboard",
    "xkb_layout_names": [
      "English (US)",
      "Russian (legacy)"
    ],
    "xkb_active_layout_index": 1,
    "xkb_active_layout_name": "Russian (legacy)"
  }
}

and switching back

{
  "change": "xkb_layout",
  "input": {
    "identifier": "0:0:X11_keyboard",
    "name": "X11 keyboard",
    "vendor": 0,
    "product": 0,
    "type": "keyboard",
    "xkb_layout_names": [
      "English (US)",
      "Russian (legacy)"
    ],
    "xkb_active_layout_index": 0,
    "xkb_active_layout_name": "English (US)"
  }
}

description of SWAY IPC: https://www.mankier.com/7/sway-ipc

**Comment by johanmalm** [comment]
This is quite an existential question for `labwc`.

`labwc` currently only understands the Wayland protocol, so it cannot be controlled using dbus, swaymsg-style-unix-socket-ipc or other IPC technology.

My preference is to keep it that way and try to stay within the eco-system of common Wayland protocols including the `wlroots` ones (https://gitlab.freedesktop.org/wlroots/wlr-protocols) and possibly `riverwm` protocols (https://github.com/riverwm/river/tree/master/protocol). I suggest only designing specific `labwc` protocols if really necessary.

`sway-ipc` would be a lot of work to implement and is unlikely to be the most elegant solution for `labwc` (elegant as in simplest+sufficient). If it turns out to be the only sufficient solution to enable the type of integration you've described above, then let's consider if the benefits match the costs (effort and loss of code simplicity primarily)

A good starting point here would be to research how other compositors (for example `river` and `hikari`) deal with this and reach out to their devs for thoughts on solutions.

Bespoke IPC has come up a few times, but we've not really got to that stage in development yet. Stabilizing current scope and fixing issue is my priority. We do not want to spend time on an expanding scope with shiny new features until the project is reliable at its current scope.

@ARDiDo @bi4k8 @Joshua-Ashton @jlindgren90 @Consolatis - I'd appreciate your thoughts on this. I think this is as good a place as any to start a discussion on it.

**Comment by Consolatis** [comment]
My thoughts:

Please do not implement any kind of custom IPC in labwc. Same for own/custom wayland protocols.
If this functionality is required it should be added to [wayland-protocols](https://gitlab.freedesktop.org/wayland/wayland-protocols) and then implemented here.

The wlr ones are a nice stopgap to work around the apparent inability of the wayland-protocols maintainers to actually get protocols merged. See [1] or [2] or [3] or [4] and the dates they were proposed and the missing NACKS.

This question is the base of why wayland compositors - other than Gnome (with GTK) and KDE (with Qt) - and traditional desktop environments like XFCE / Mate / LXDE / LXQt have such a hard time to provide a full wayland desktop experience.
You can add custom IPC or wayland protocols all you want and provide everything a full desktop environment requires but are completely incompatible with everybody else. In my opinion this kind of fragmentation is what is actively hindering wayland adoption.

[1] https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/28
[2] https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/40
[3] https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/60
[4] https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/59

**Comment by ARDiDo** [comment]
I agree with @Consolatis. Adding yet another type of IPC that wayland based applications have to deal with would create more problems than it is worth.

Implementing `sway-ipc` doesn't feel necessary either. It would greatly complicate things on our end, only to achieve the same result that can be hacked together with `wtype` to emulate keybindings, and maybe updating a few text files containing compositor information.

Bit of a side note, but we may want to consider adding support for keybindings with multiple actions.

**Comment by johanmalm** [comment]
That's for feedback. Sounds like we're aligned.
I've summarized the position here https://github.com/labwc/labwc-acceptance-criteria#31-IPC

**Comment by Consolatis** [comment]
> to solve a short term problems.
`s/ a// || s/problems/problem/`
