### ISSUE TITLE
Labwc misplaces titlebar on small window

### ISSUE THREAD

**Issue by jjramsey** [labwc/labwc#1947]
Here's what it looks like:
![swappy-20240629_221901](https://github.com/labwc/labwc/assets/25332524/0c9f46d4-f18e-4bc8-a7c9-8ca8b4df88fc)

Unfortunately, the titlebar doesn't have a place where a pointer can hold and drag to move the window (but Alt-click-drag still works).

This window is from Workrave.

**Comment by Consolatis** [comment]
Is this an X11 or a wayland native window? (`[xdg-shell]` or `[xwayland]` when pressing `A-Tab`).

**Comment by 01micko** [comment]
It runs under Xwayland - I just tested it out, same as above screencap.

**Comment by droc12345** [comment]
You might try running from a terminal, "env GDK_BACKEND=x11 workrave" to see if more messages show
or perhaps a clue why it segfaults.

**Comment by tokyo4j** [comment]
I could't reproduce this, but this weird behavior is expected. We are restricting the window geometry in "configure" events, but not restricting the geometry the client submits. And if the submitted geometry is smaller than minimal values, SSD is not updated (introduced with #1762), so SSD remains in the weird look like in the picture. We need more sophisticated solution for this.

**Comment by droc12345** [comment]
tokyo4j , I have a question, that this brings up.
When we provide ssd, is that bolted onto the app or is all of it in container?

Much of this would be easier to fix if the window and the ssd were treated as one object, ie a container has both window and ssd. 

The reason I wondered about this is I'm looking at possibly adding opacity to windows and don't really want to
try and handle ssd separate from window, much better to treat them as a whole, before sending to output.

**Comment by tokyo4j** [comment]
>  When we provide ssd, is that bolted onto the app or is all of it in container?

With the scene-graph API, we have `view->scene_tree` for every window and it contains `view->scene_node` and `view->ssd` as children. `view->scene_node` represents the tree for surfaces drawn by the app and `view->ssd` represents tree for all ssd components like buttons, borders, titlebars, drop-shadows, and extent for resize handle. The surface geometry and ssd geometry are mostly synced in `view_moved()` when the app commits its geometry, but in this issue I guess it's not because ssd rejects to be resized to very small values. (Note that I'm not expert about ssd.)

> The reason I wondered about this is I'm looking at possibly adding opacity to windows and don't really want to
try and handle ssd separate from window, much better to treat them as a whole, before sending to output.

I think sway handles this well. To apply opacity for a container, it traverses the child nodes of the container tree and calls `wlr_scene_buffer_set_opacity()` for each buffer nodes. If we apply the same thing for labwc, we can traverse the child nodes of `view->scene_tree`.

**Comment by jjramsey** [comment]
> Is this an X11 or a wayland native window? (`[xdg-shell]` or `[xwayland]` when pressing `A-Tab`.)

Wayland native. This is the latest beta of Workrave (and requires passing `-DHAVE_WAYLAND:BOOL=TRUE` to its cmake configure line to build on Wayland properly).

**Comment by jjramsey** [comment]
Is there any reason why you wouldn't simply want to expand the Workrave window to accommodate the decorations?

**Comment by tokyo4j** [comment]
> Is there any reason why you wouldn't simply want to expand the Workrave window to accommodate the decorations?

It's just because workrave doesn't resize its window as labwc requests (with `xdg_toplevel.configure` event) for some reason. I guess Wayland support for workrave is still work-in-progress.

**Comment by jjramsey** [comment]
That's odd. When I tried Workrave under Wayfire and KDE Wayland, the window was resized enough to accommodate window decorations. Maybe Wayfire used a different request?

If Workrave isn't resizing when it should, that probably *is* an issue to submit to Workrave, though.

**Comment by stefonarch** [comment]
I didn't follow all but Qt has a bug now that allows ridiculous resizing, that's featherpad:

![immagine](https://github.com/labwc/labwc/assets/10681413/52a2eab9-5a3e-485a-8ec4-f107fde1c74d)

**Comment by Consolatis** [comment]
> It looks like the limit is by all buttons widths summed up, with or without decoration.

Correct, the `without decorations` part is still an open issue. This specific minimal size should only matter for windows with server side decorations. However, we likely need \*some\* minimal size even for windows without server side decorations because finding a 1px x 1px window without server decorations and recovering from that state seems pretty much impossible from a UX perspective.

**Comment by jjramsey** [comment]
Turned out Workrave was using CSD under Wayfire at the time.
