### ISSUE TITLE
X11 resources set by xrdb don't survive xwayland restart

### ISSUE THREAD

**Issue by jech** [labwc/labwc#1958]
I've got the following in my `autostart` file:
```
xrdb < ~/.Xresources
```
Occasionally, the X resources are not taken into account after labwc starts, and I need to manually run `xrdb < ~/.Xresources` from a terminal.

Is that an issue with labwc?  Or am I putting the X resources at the wrong place?

**Comment by ahesford** [comment]
`xrdb` commands in the autostart will never have the intended effect, because `Xwayland` will terminate itself after a period of inactivity. Thus, you launch the X server to set the resources, and it dies if you don't start an X11 client right away.

Xwayland seems to read `~/.Xdefaults` by default (not sure if this is a wlroots thing or an Xwayland thing), so I suggest

    ln -s .Xresources ~/.Xdefaults

and drop the autostart.

**Comment by jech** [comment]
> Xwayland seems to read ~/.Xdefaults by default

I could be wrong, but I belive that `.Xdefaults` is an older mechanism, that was made obsolete by xrdb.  As far as I rememebr, Xdefaults are read by the older applications at startup, they are not stored in the server.

What's the right way to run a script whenever Xwayland is started?

**Comment by ahesford** [comment]
You might be right about the application taking responsibility for reading Xdefaults.

If your applications aren't reading Xdefaults (it seems to work for urxvt and gimp in my tests; I don't routinely run other clients), you'll have to either keep the X server alive by running a client constantly, wrap Xwayland to do what you need, or patch wlroots.

**Comment by jech** [comment]
I see, thanks.

> If your applications aren't reading Xdefaults

Xdefaults is not a suitable replacement for Xresources, since it is not forwared over `ssh -X`.  I'll file an issue against wlroots, and see what they have to say.

**Comment by Consolatis** [comment]
xwayland can be run in two separate ways within wlroots
- always running 
- the "lazy" approach: only open the X11 socket and wait for a client to connect and tell xwayland to terminate itself when it hasn't seen a client in like 10 seconds

Labwc uses the "lazy" approach due to obvious benefits when not using X11 clients continuously. Technically, labwc could implement another script that is run automatically whenever xwayland starts up to cater for use-cases like xrdb.

**Comment by jech** [comment]
A simple solution would be to run a user-defined script, say `autostart-x11`, whenever we launch Xwayland.

**Comment by ahesford** [comment]
Although a persistent Xwayland can work around the problem, the inability to properly initialize the X server on launch is orthgonal to the laziness issue.

As for adding an `autostart-x11`, script, I don't believe we control the lifetime of the X server, so that would be up to wlroots.

**Comment by jech** [comment]
That's an entertaining conundrum :-)

**Comment by Consolatis** [comment]
> As for adding an `autostart-x11`, script, I don't believe we control the lifetime of the X server, so that would be up to wlroots.

Right, but we do get a notification whenever X11 is starting up. We are using it to fetch some X11 atoms currently. We could absolutely just execute some random script on that point.

**Comment by ahesford** [comment]
Both approaches (persistence and support for an xinitrc) are now proposed in #1961.

**Comment by Consolatis** [comment]
Persistence has been merged: https://labwc.github.io/labwc-config.5.html#entry_core_xwaylandpersistence

**Comment by jech** [comment]
Reported here: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3863

**Comment by jech** [comment]
I've just switched to 0.7.3, and I can confirm that `<xwaylandPersistence>yes</xwaylandPersistence>` solves my issue quite nicely.  Thanks.
