### ISSUE TITLE
Doubled shortcuts depending on layout

### ISSUE THREAD

**Issue by stefonarch** [labwc/labwc#1991]
We had an issue about french keyboard layout with the shortcut added under an english layout  and I remembered  `layoutDependent=`:
```
    <keybind key="W-z" layoutDependent="yes">
      <action name="ToggleDecorations"/>
    </keybind>
```
which works as intended (between german and italian/english layout Z and Y get inverted). 
But i noticed that adding this shortcut with  ` layoutDependent="no"` (or omitting it) under italian keyboard only W-z is toggling decorations but if I switch to german layout _both_ W-z and W-y are working shortcuts, but only there, switching back only the original is considered.

**Comment by Consolatis** [comment]
Labwc has a 3 stage detection logic for keybinds with the first one matching getting used:
- keycodes (physical keys) which are set on initialization based on the first match in any layout for the sym ("z" in your case)
- keysym based on the current layout
- keysym without modifier based on the current layout

Setting `layoutDependent="yes"` skips the first stage.

So what happens there is that due to italian layout being the first it will find the physical key in that layout that corresponds to "z" and store it in its internal list. Thus regardless of the layout in use later that same key will always trigger the keybind. For `W-y` on the german layout (which actually has a "z" printed on it on a german keyboard; y and z are switched) if there is no other keybind with `W-y` the first stage will not find a keybind thus the next stage is entered and as the physical `y` key on a non german keyboard using the germal layout is in fact a `z` the sym matches and thus the keybind is executed.

If you run labwc nested with `-d` you should get log messages like
- `keycode matched`
- `translated keysym matched`
- `raw keysym matched`

**Comment by stefonarch** [comment]
In fact I wasn't sure if that is an issue or not, could be  transformed in discussion or closed, thanks for the explanation!
