### ISSUE TITLE
Move `scrollFactor` to `libinput` section

### ISSUE THREAD

**Issue by kabishchev** [labwc/labwc#2033]
Hello. I suggest moving the `scrollFactor` option from the `mouse` section to the `libinput.device` section, so that you can set a different scroll speed for each peripheral device. For example, I need to set a lower scroll factor for my laptop's touchpad as it seems too fast, but then my mouse scroll speed becomes very slow.

**Comment by tokyo4j** [comment]
I agree that per-device `scrollFactor` is useful. The problem here is that scroll factor is not actually in libinput API, but I think most users don't care about that weirdness. Another option is adding `<scrollFactor deviceName="">`, but putting it in `libinput.device` feels cleaner to me as `pointerSpeed` and `naturalScroll` is also there.

**Comment by kabishchev** [comment]
Thank you for your reply.

> putting it in `libinput.device` feels cleaner to me as `pointerSpeed` and `naturalScroll` is also there.

Yeah, that's exactly how it's done in swaywm as well. They don't have a dedicated libinput API section though, just `input` for all the various options.

```
input "1267:12397:ELAN2202:00_04F3:306D_Touchpad" {
	tap "enabled"
	natural_scroll "enabled"
	accel_profile "adaptive"
	pointer_accel "-0.115"
	scroll_factor "0.25"
}
```
