### ISSUE TITLE
desk*.xbm (omnipresent) buttons cannot be styled/colorized

### ISSUE THREAD

**Issue by stefonarch** [labwc/labwc#2111]
Maybe I'm missing something, here it's always black.

https://github.com/user-attachments/assets/4f496e37-3734-4b05-85f1-6e22dde9c863

`themes.rc`:

## BUTTONS
```

window.active.button.iconify.unpressed.image.color: #f59335
window.active.button.max.unpressed.image.color: #a1d569
window.active.button.close.unpressed.image.color: #ef6b7b
window.active.button.menu.unpressed.image.color: #4ec2e8
window.active.button.desk.unpressed.image.color: #f59335
window.active.button.shade.unpressed.image.color: #a6a228

window.inactive.button.iconify.unpressed.image.color: #939597
window.inactive.button.max.unpressed.image.color:#939597
window.inactive.button.close.unpressed.image.color: #939597
window.inactive.button.menu.unpressed.image.color: #939597
window.inactive.button.desk.unpressed.image.color: #939597
window.inactive.button.shade.unpressed.image.color: #939597
```

**Comment by Consolatis** [comment]
Try with `window.(in)active.button.omnipresent.unpressed.image.color`.

**Comment by stefonarch** [comment]
Ok, never thought of that, as for all other the filename is used.

**Comment by Consolatis** [comment]
Thoughts regarding the theme var naming @ahesford ?

**Comment by ahesford** [comment]
I didn't read the Openbox spec when adding the omnipresent button. It seems what I call the "Omnipresent" mouse context is called "AllDesktops" in Openbox.

I'd propose one of two things:
1. Moving the context name to "AllDesktops" and changing the theme variable to "desk" to agree with the image names, or
2. Accepting "AllDesktops" and "Omnipresent" as synonyms for the mouse context, and then accepting both "desk" and "omnipresent" as synonyms in the theme file. If both exist, the "omnipresent" variant would take precedence because it would be specific to labwc.


I think I favor the second option because "Omnipresent" seems a nicer description than "AllDesktops", but I could go either way.

**Comment by Consolatis** [comment]
@stefonarch JFYI, latest master now uses `window.(in)active.button.desk.unpressed.image.color`.
