### ISSUE TITLE
Enriching the <query> API to match that of openbox'

### ISSUE THREAD

**Issue by orfeasxyz** [labwc/labwc#2126]
Openbox offers a lot of different query options especially ones related to the current window state.  

Reference: https://redtide.github.io/openbox-wiki/Help/Actions/#if

**Comment by johanmalm** [comment]
Sounds interesting.

We generally take the view that we wait for someone to write a patch or describe a particular use-case rather than just copying all of Openbox's options. But having said that - am happy to merge to merge those types of query variants.

Out of interest - is there a particular use-case you foresee?

**Comment by orfeasxyz** [comment]
> Sounds interesting.
> 
> We generally take the view that we wait for someone to write a patch or describe a particular use-case rather than just copying all of Openbox's options. But having said that - am happy to merge to merge those types of query variants.
> 
> Out of interest - is there a particular use-case you foresee?

I see your concern regarding the use-case of these features. One quick use case I can think of is the W-Right followed by W-Up to snap a window to the upper right region without having a separate keybind for it like this:

```xml
...
<keybind key="W-U">
  <action name="If">
    <query>
      <snapped>right</snapped>
    </query>
    <then>
      <action name="SnapToRegion" region="up-right"/> <!-- up-right region defined elsewhere -->
    </then>
  </action>
</keybind>
...
```
