### ISSUE TITLE
Add global configurations in /etc/xdg/labwc

### ISSUE THREAD

**Issue by redtide** [labwc/labwc#216]
Like in the original openbox, use a generic, read only global configuration, so that the system is functional after installation. At least here once installed and started, it shows only the cursor.

**Comment by johanmalm** [comment]
We read `/etc/xdg/labwc/rc.xml` in case a distribution package maintainer wish to set a system override.

https://github.com/labwc/labwc/blob/5f27356fc1f791c2497d1874ec02ed1427554981/src/common/dir.c#L24

As one of the developers, I prefer not to ship a `/etc/xdg/labwc/rc.xml` because I want labwc to be easy to use out of the box without needing to spend time setting up configuration. For me, that includes being able to build and run without having to do a `ninja -C build/ install`. For this reason, we have set more sane theme defaults than openbox did.

Openbox theme defaults are mostly black and white, which isn't particularly great. As a result, mosto themes set all options, so in practice we haven't lost any theme backward compatibility by setting sensible defaults.

Openbox doesn't actual start if it can't find a theme. As it's normally packaged with Clearlooks, this is not a problem, but for labwc I thought this was a bit hard-line.

theme_builtin() applies a theme that is similar to vanilla GTK

https://github.com/labwc/labwc/blob/5f27356fc1f791c2497d1874ec02ed1427554981/src/theme.c#L78

Openbox will also just start with a blank desktop and a cursor (even with the system-wide rc.xml). The background/panel/etc are started by the user in `~/.config/openbox/autostart`.


Try starting with `labwc -c <your-favourite-terminal>` and you'll see that the default window decoration is a nice gray with rounded corners :smile:

**Comment by redtide** [comment]
Thank you for the explanation, that's fine to me then, I'll close this.
While at it:
> Try starting with labwc -c <your-favourite-terminal> and you'll see that the default window decoration is a nice grey with rounded corners

Now I see from where that comes from, I thought it was some parsing problem or a wrong theme directory from my side:
I have a `~/.local/share/themes/Onyx-Citrus/openbox-3/themerc` original ob theme setting but it doesn't work; how to fix it?

**Comment by johanmalm** [comment]
Have you got a local rc.xml with theme.name set to Onyx-Citrus

https://github.com/labwc/labwc/blob/master/docs/rc.xml

**Comment by redtide** [comment]
yes, I was using the openbox one adapted, even using the simple one you linked with the name set it doesn't work, will check later again if I did something wrong.

**Comment by redtide** [comment]
Meh I give up for a while since I miss lot of things using Wayland and I have no much time to reconfigure the system and solve other issues (some applications refuse to autostart) to match the one I have on x11, I'll appreciate if someone could test and confirm that the black glossy Onyx-Citrus theme works with labwc, it's the only one I use from a long time.
