### ISSUE TITLE
Thunderbird cannot shrink back from maximized to normal window properly

### ISSUE THREAD

**Issue by knm100** [labwc/labwc#2183]
Please see the video.

https://github.com/user-attachments/assets/2035f25c-7d31-49e4-9a94-2e5266826463

Is it an issue of thunderbird or labwc? 

Edited:
the output messeage of command `WAYLAND_DEBUG=client  /usr/bin/thunderbird`
[1.txt](https://github.com/user-attachments/files/17142004/1.txt)

**Comment by tokyo4j** [comment]
Your log file has no wayland messages. Is your thunderbird running in X11?

Also, does your problem happen in both labwc 0.8.0 and git master?

**Comment by knm100** [comment]
> Your log file has no wayland messages. Is your thunderbird running in X11?
I'm sorry,  Please refer to the following log. and I petty sure the thunder was running in wayland, because i complied labwc with `Dxwayland=disabled`
[2.txt](https://github.com/user-attachments/files/17145254/2.txt)


> Also, does your problem happen in both labwc 0.8.0 and git master?

this Behavior in my video  appeared in the lastest git rev that was ran in vmware.  and  I sure this kind of Behavior im my video had been appearing since labwc 0.70 at least

**Comment by tokyo4j** [comment]
Hmm... perhaps the workaround for Qt apps is causing the issue:

https://github.com/labwc/labwc/blob/9b56cb62261103840c8d0a1fbff5df8207f3501c/src/xdg.c#L154-L173

Could you run labwc with `WAYLAND_DEBUG=server labwc -d 2> log.txt` and show me the log?

**Comment by knm100** [comment]
reproduce the issue at the last time  shrinking back from maximized to normal
[log.txt](https://github.com/user-attachments/files/17146953/log.txt)

**Comment by stefonarch** [comment]
Just a note: never saw that with thunderbird here.

**Comment by tokyo4j** [comment]
From my observation, here's what happened:
1. Thunderbird maintains a toplevel surface and a subsurface
2. Labwc configures the toplevel with the windowed geometry
3. Thunderbird doesn't reply it with a commit within 100ms
4. Labwc cancels the configure event and set `view->pending` to the maximized geometry
5. Thunderbird resizes the window (with `set_window_geometry`) and the buffer attached to the toplevel surface, but doesn't update the buffer attached to the subsurface
6. The branch I quoted [above](https://github.com/labwc/labwc/issues/2183#issuecomment-2376559179) is taken since `view->pending` is in the maximized geometry, the window is in windowed geometry, and the surface+subsurface extent (returned from `wlr_surface_get_extends()`) is in maximized geometry. Thus the window decoration is still in the maximized geometry.
7. Thunderbird finally resizes the buffer attached to the subsurface to the windowed geometry
8. But labwc doesn't react to it since we only listen to commits on the toplevel surface

So the solutions I came up with are:
1. Remove the workaround above for Qt apps
2. Also listen for commits on subsurfaces

But I'm not sure (1.) is fine. And for (2.), AFAIK wlroots doesn't provide a way to listen for commits on subsurfaces, which are encapsulated inside `wlr_scene_xdg_surface_create`.

**Comment by johanmalm** [comment]
Until we find a sensible technical way forward, could we turn up the timeout a bit?

Whilst none of us particularly liked the Qt workaround, it's also slightly awkward to remove it because the Qt eco-system doesn't move that fast and if we remove it, we have the ##1194 bug. @jlindgren90 can you remember if we raised a ticket with Qt for applications failing to call `set_window_geometry()` after a configure request?

**Comment by jlindgren90** [comment]
> The branch I quoted https://github.com/labwc/labwc/issues/2183#issuecomment-2376559179 is taken since view->pending is in the maximized geometry, the window is in windowed geometry, and the surface+subsurface extent (returned from wlr_surface_get_extends()) is in maximized geometry. Thus the window decoration is still in the maximized geometry.

So to make sure I understand, thunderbird has updated the top-level surface extent at this point, but not the subsurface?

If so this is an unfortunate conflict between two different workarounds (the configure timeout and the check for out of date window geometry).

In the branch that checks the window geometry, what if we look at only the top-level surface extent and ignore subsurfaces? Effectively this should narrow the workaround a bit. I don't think we should be letting subsurface extents override the declared window geometry.

**Comment by tokyo4j** [comment]
> So to make sure I understand, thunderbird has updated the top-level surface extent at this point, but not the subsurface?

Yes, as far as what I saw from the log.

> In the branch that checks the window geometry, what if we look at only the top-level surface extent and ignore subsurfaces? Effectively this should narrow the workaround a bit. I don't think we should be letting subsurface extents override the declared window geometry.

Yeah it will work around the issue if my observation is correct.

I was able to reproduce the issue by un-maximizing the thunderbird window while stressing the CPUs with Linux kernel compilation. I'll try the suggested workaround and see if it fixes the issue.
