### ISSUE TITLE
Is there a way to gen an open window size and location info

### ISSUE THREAD

**Issue by skozlovski** [labwc/labwc#2233]
Hi,
I am starting to look at the labwc and can not figure out a way to determine the coordinates and size of an open window.  Perhaps there is a cli command or a hot key to accomplish it.

Thank you for your help

**Comment by tokyo4j** [comment]
This window rule moves and resizes the `foot` window to a specific geometry:

```xml
<windowRule identifier="foot">
      <action name="MoveTo" x="0" y="0" />
      <action name="ResizeTo" width="300" height="300" />
    </windowRule>
```

You will see a flicker though. We'll fix it at some point.

**Comment by skozlovski** [comment]
Thank you. Yes, I already got very familiar with rc.xml and I find it very powerful. However, my question was about how to find out the coordinates and size of an already opened window. In xorg, I could use xwininfo to get the window information, but in labwc xwininfo does not work.

**Comment by tokyo4j** [comment]
Oh, sorry. Unfortunately, labwc doesn't expose the information about window positions/sizes.

Could you tell me why you want to know those information?

**Comment by kenzoi** [comment]
I would like to have this information too.
My use is fairly simple, I just use Microsoft Teams on my job and since there is no Teams native I use from the Browser and then I use a simple script to keep my online status when I'm available/working so now on Xorg the script save current position of mouse, focus Teams window, move mouse and recover original position.

On Xorg xdotool solves this.
On Wayland I think it's possible on KDE with kdotool, on Gnome creating an extension or enabling unsafe mode + dbus messages and on Sway through its IPC (I think they don't expose cursor actual location) may be doable using focus windows + tabs. 

Maybe labwc could implement some power user / scripting features behind a flag.
I know there is a huge effort to not use custom IPC and rely almost exclusively on Wayland Protocols to achieve maximum integrations and track standards and I really think this is awesome, but sometimes I'm afraid that some features will never be a Wayland Protocol, specially these stuff that somehow can compromise privacy. 

Thank you

**Comment by Consolatis** [comment]
You could archive something similar with [wlrctl](https://git.sr.ht/~brocellous/wlrctl). Although I don't see how you could move the cursor back to its original position. Writing some char and deleting it again should result in the same behavior though. You could also store the previously focused window and then give it focus again when done.
Something along the lines of
```
wlrctl window focus title:Teams
wlrctl pointer move 100 100
```

Another option could be to use the X11 backend of the browser.
I have to admit that this is a pretty weird use-case though, doesn't teams have something to manually set the online status?

**Comment by kenzoi** [comment]
Oh, that's nice! I've forgotten about wlrctl I tried it once some months ago to do another thing.
This will solve my problem! I can use wlrctl and spam 1 or 2 tab keys and back to my original focused window, leaving my cursor where it was untouched.
I'll wait for the next version that I think will implement the "stable window ID" protocol, and then I'll probably back to Labwc on this pc. 

On Microsoft Teams you can manually set the online status, but unfortunately he puts you in the away status automatically after 5 min of idle and this behavior can't be changed within the app as a user. There is a newer Browser API that may allow detecting idle activity using the SO/Desktop info, but it's not yet adopted by Teams and also I don't know if it has or will have Linux/Wayland support. 

Thanks!
