### ISSUE TITLE
How to use ibus with labwc?

### ISSUE THREAD

**Issue by archisman-panigrahi** [labwc/labwc#2285]
I am using labwc on Raspberry Pi OS.

I am unable to use ibus. While ibus works just fine in x11 (and also on wayfire with wayland), I am unable to even start ibus in labwc+wayland. Running `ibus-daemon -drx` produces no output and does nothing.

**Comment by ahesford** [comment]
Please consult the Raspberry Pi OS or IBus support forums for help configuring and using IBus. If you can describe a basic test workflow that does not depend on Raspberry Pi OS AND produces observable results in another windowing environment, document it here and we will investigate.

**Comment by tokyo4j** [comment]
I couldn't get ibus work under wayfire, but if it stopped working after the migration to labwc, maybe it's because labwc doesn't support input-method-v1. Looking at the wayfire source code, it seems to support input-method-v1, in addition to input-method-v2 that wlroots provides the implementation for.

As we usually don't deviate from what wlroots/sway supports (cosmic-workspace is exceptional here), it's unlikely that we add support for input-method-v1 any time soon. So for now, I can only encourage users to use Fcitx5 which supports input-method-v2.

**Comment by stalkerg** [comment]
This is why under Wayland we are usually using fcitx

**Comment by archisman-panigrahi** [comment]
Now I understand that this is not a labwc bug, but a decision not to support  input-method-v1.

Unfortunately, my language (Bengali/Bangla) is not as well-supported in fcitx as it is in ibus. I will have to wait for ibus to support input-method-v2.

Till then, can we keep the issue open? Even if ibus implements  input-method-v2, it may take some coordinated input from ibus devs and labwc devs so that ibus smoothly works on labwc.

**Comment by ahesford** [comment]
If IBus adopts support for `input-method-v2` and doesn't work with labwc's implementation, please feel free to open an issue. Until then, there is nothing actionable here.

**Comment by archisman-panigrahi** [comment]
Here is a workaround for anyone who wants to use ibus with labwc right now.

First, download and [compile](https://github.com/ibus/ibus/wiki/DevGuide) the wayland-v2 branch of ibus with initial `input-method-v2` support - https://github.com/fujiwarat/ibus/tree/wayland-v2

Now, `ibus engine ibus-avro` should switch the input language to Bangla, and `ibus engine xkb:us::eng` should switch the language back to English.

Create two desktop files which will execute these commands and add them to the panel for easy access. It may be possible to assign keyboard shortcuts to these commands. The GUI system tray of ibus is not working yet, but work is in progress.
