### ISSUE TITLE
How to disable the window theme?

### ISSUE THREAD

**Issue by linux36524** [labwc/labwc#2292]
like this：
https://img.erpweb.eu.org/imgs/2024/11/faa7659d9aa0293e.png

**Comment by Consolatis** [comment]
Please attach the image directly to the issue rather than hosting it somewhere else.

As for your question you could set [decoration](https://labwc.github.io/labwc-config.5.html#entry_core_decoration) to `client`. E.g.
```xml
<core>
	<decoration="client" />
</core>
```

This should make all wayland native applications prefer client side decorations rather than labwc side ones. You can additionally add a [window rule](https://labwc.github.io/labwc-config.5.html#entry_windowrules_windowrule_serverdecoration=) to force all clients to have no labwc generated decorations but you may end up with windows without any decorations at all:
```xml
<windowRules>
	<windowRule identifier="*" serverDecoration="no" />
</windowRules>
```

**Comment by linux36524** [comment]
> Please attach the image directly to the issue rather than hosting it somewhere else.
> 
> As for your question you could set [decoration](https://labwc.github.io/labwc-config.5.html#entry_core_decoration) to `client`. E.g.
> 
> ```
> <core>
> 	<decoration>client</decoration>
> </core>
> ```
> 
> This should make all wayland native applications prefer client side decorations rather than labwc side ones. You can additionally add a [window rule](https://labwc.github.io/labwc-config.5.html#window_rules) to force all clients to have no labwc generated decorations but you may end up with windows without any decorations at all:
> 
> ```
> <windowRules>
> 	<windowRule identifier="*" serverDecoration="no" />
> </windowRules>
> ```

Thank you very much
