### ISSUE TITLE
How to get active keyboard layout?

### ISSUE THREAD

**Issue by Sunderland93** [labwc/labwc#236]
I want to use waybar and create keyborad layout module, but all I have find is Sway-only (using swaymsg). Is there a way to get current keyboard layout from Labwc like this: https://github.com/mhdzli/dotfiles/blob/master/src/.local/bin/wkblayout ?

**Comment by Consolatis** [comment]
I don't actually know if the [wayland protocol](https://gitlab.freedesktop.org/wayland/wayland/-/blob/main/protocol/wayland.xml) supports querying or setting the keyboard layout.
I have `XKB_DEFAULT_LAYOUT=de` in `~/.config/labwc/environment` though which just sets a usual environment var that could be parsed in waybar. That would give you the current layout but doesn't really provide a way to change it without restarting labwc.

labwc doesn't have any kind of custom IPC on purpose.

**Comment by Consolatis** [comment]
I don't think think it'll change. When `~/.config/labwc/environment` changes and you `SIGHUP` labwc it should update the environment for newly spawned processes (from the compositor itself, like from a keybinding).
But I am not sure if its actually all the helpful.

**Comment by s3rj1k** [comment]
> I don't think think it'll change. When `~/.config/labwc/environment` changes and you `SIGHUP` labwc it should update the environment for newly spawned processes (from the compositor itself, like from a keybinding). But I am not sure if its actually all that helpful.

Yea, I assumed so.

**Comment by s3rj1k** [comment]
So, it is possible to set ```XKB_CURRENT_LAYOUT``` or ```XKB_ACTIVE_LAYOUT``` inside labwc process, so some third=party application can get information on currently active layout?

Not talking here about changing layout programmatically, only to be able to somehow display current layout information.

**Comment by s3rj1k** [comment]
@Sunderland93 Where you able to somehow solve this issue?

**Comment by s3rj1k** [comment]
@Consolatis I assume it's up to labwc to provide some details about currently active XKB, according to
https://unix.stackexchange.com/a/309729

**Comment by s3rj1k** [comment]
Please re-open this issue

**Comment by johanmalm** [comment]
@s3rj1k I will have a go a writing a client that prints the keymap layout name. Shouldn’t be that hard. 
Probably won’t get a chance to think about it until the weekend. If anyone else is having a go at this, let me know so we don’t duplicate effort.

**Comment by johanmalm** [comment]
Sorry - forgot all about this one.
Here is attempt number 1: https://github.com/johanmalm/keyboard-layout
Appreciate feedback

**Comment by 01micko** [comment]
Forgot too. Works here.

> Sorry - forgot all about this one. Here is attempt number 1: https://github.com/johanmalm/keyboard-layout Appreciate feedback

**Comment by s3rj1k** [comment]
> Sorry - forgot all about this one. Here is attempt number 1: https://github.com/johanmalm/keyboard-layout Appreciate feedback

Can this be somehow included in labwc repo, like for example contrib folder?

**Comment by Consolatis** [comment]
Hm.. Maybe even along with tweaks, menu generator, GTK style converter?

Having the dev work being done in their respective repos (including their own issues / PRs) is nicer than having it here but it would also give them more exposure. Maybe we could just do periodic snapshots from those repos and have a somewhat recent copy (+ instructions where to file issues / PRs) in `/contrib/`?

**Comment by johanmalm** [comment]
I guess there are no rules for a contrib/ directory, but in view the following applies:

- unorganized
- contributed by the community
- not part of build system
- not part of test suite
- not part of documentation
- not installed with the main software
- not supported by maintainers/devs
- independent coding style
- intended for little scripts, config files, and so on

I prefer to keep `labwc-tweaks`, `labwc-gtktheme` and `labwc-menu-generator` in separate repos for the following reasons: They are small project in their own right, with different dependencies, unit-tests, issue trackers and so on (okay - `labwc-gtktheme` does not have a set of unit tests yet, but I need to set some up to sensibly take the next step in its development). Adding these to the `labwc` repo would also add unwanted (by me :smile:) commit noise.

I guess `keyboard-layout` is slightly different in that it's not likely to change much, is a single file, has no separate dependencies, and so on. I'm reluctant to add it to a `contrib/` though because I think it's the wrong solution for querying the keyboard because it actually grabs keyboard-focus for a short period, so is not something you'd want in a panel or similar (and therefore I'm not sure what the use-case is). That's why I haven't even renamed it to `labwc-keyboard-layout` and moved it to the `labwc` organization.

My preferred approach for giving small package exposure is to add it to the labwc organization and refer to it from the integration page (or similar) on labwc.github.io

**Comment by s3rj1k** [comment]
> I guess `keyboard-layout` is slightly different in that it's not likely to change much, is a single file, has no separate dependencies, and so on. I'm reluctant to add it to a `contrib/` though because I think it's the wrong solution for querying the keyboard because it actually grabs keyboard-focus for a short period, so is not something you'd want in a panel or similar (and therefore I'm not sure what the use-case is). That's why I haven't even renamed it to `labwc-keyboard-layout` and moved it to the `labwc` organization.

So there is still original keyboard problem present, sway has custom protocol inplace for this so other panels can indicate KBD layout.

How about adding this custom protocol as opt-in compile time option?

**Comment by kyak** [comment]
Hey guys,

I'd appreciate a little bit more information regarding to how use https://github.com/johanmalm/keyboard-layout

From what I understand, `keyboard-layout` is supposed to be a simple command-line utility that would sit there is the loop and print current keyboard layout to the stdout. From the other side, there must be a custom waybar plugin that would understand what `keyboard-layout` says and display the current keyboard layout. Is this correct?

I've tried to build and run `keyboard-layout`. It runs indeed and print current keyboard layout correctly. After that, it exits and I'm not able to type anything at all. I have to reset the computer.

I'm determined to make it working, just need some help and hints. The keyboard layout indicator is a must-have for my daily workflow.

**Comment by kyak** [comment]
> FYI if your using only 2 layouts[ there is a workaround](https://github.com/stefonarch/LXQt-Wayland-files/blob/main/lxqt-panel.md#keyboard-statelayout-indicator), working in a custom plugin in waybar and in lxqt-panel/custom command plugin.

Thanks for pointing to the workaround, I'll have a look into it

**Comment by kyak** [comment]
Ok, this workaround kinda works for my use case. I'll leave this information here for future people.

1. In `.config/labwc/environment`:

```
XKB_DEFAULT_LAYOUT=us,ru
XKB_DEFAULT_OPTIONS=grp:caps_toggle,grp_led:scroll
```

2. In `.config/waybar/config`:

2.1. Add "custom/language" to the modules, e.g.
```
"modules-right": ["pulseaudio", "network", "cpu", "memory", "temperature", "backlight", "sway/language", "custom/language", "battery", "clock", "tray"],
```

2.1. Add "custom/language" module:
```
"custom/language": {
  "exec": "~/bin/language.sh",
},
```

3. Contents of `~/bin/language.sh`:

```
#!/usr/bin/bash
while true; do
  if [ "$(cat /sys/class/leds/input5\:\:scrolllock/brightness)" == "1" ]; then echo ' RU '; else echo ' US '; fi
sleep 1
done
```

I decided to do `sleep` in the bash script instead of using `interval` option of waybar custom module. Sleeping in the script is probably better than spawning this script from waybar by `interval`.
