### ISSUE TITLE
pasystray popup menu is not visible

### ISSUE THREAD

**Issue by keshto** [labwc/labwc#239]
Don't know if this is a sfwbar or labwc issue, but figured it might be interesting. When using swfbar and left clicking on the pasystray icon a menu is supposed to popup. It seems to popup, but just is not visible (confirmed by clicking where the quit would be quits the app). This is same behavior when right clicking on a tasklist item.

Issue filed with sfwbar https://github.com/LBCrion/sfwbar/issues/22

**Comment by ahmadraniri1994** [comment]
Did you try on other Wayland compositors (e.g sway) ?

**Comment by keshto** [comment]
Yes works fine on sway and Watford.

**Comment by LBCrion** [comment]
This behavior seems to be caused by gtk3 menus popped up from a layer shell window set to overlay layer. If the window is on a different layer, the menu shows up. Attached below is a minimal example triggering this behavior:


#include <gtk/gtk.h>
#include <gtk-layer-shell.h>

static void activate (GtkApplication* app, gpointer data )
{
  GtkWidget *menu, *item, *win, *label;

  menu = gtk_menu_new();
  item = gtk_menu_item_new_with_label("Item1");
  gtk_widget_show(item);
  gtk_container_add(GTK_CONTAINER(menu),item);

  win = gtk_application_window_new(app);
  gtk_layer_init_for_window (GTK_WINDOW(win));
  gtk_layer_set_layer(GTK_WINDOW(win),GTK_LAYER_SHELL_LAYER_OVERLAY);

  label = gtk_label_new("Test");
  gtk_container_add(GTK_CONTAINER(win), label);
  gtk_widget_show_all(win);
  gtk_menu_attach_to_widget(GTK_MENU(menu),label,NULL);
  gtk_menu_popup_at_widget(GTK_MENU(menu),label,
        GDK_GRAVITY_SOUTH_WEST,GDK_GRAVITY_NORTH_WEST,NULL);
}

void main (int argc, char **argv)
{
  GtkApplication *app;

  app = gtk_application_new ("org.hosers.example", G_APPLICATION_FLAGS_NONE);
  g_signal_connect (app, "activate", G_CALLBACK (activate), NULL);
  g_application_run (G_APPLICATION (app), argc, argv);
  g_object_unref (app);
}

**Comment by johanmalm** [comment]
We're currently moving across to the wlroots scene-graph API, which should fix that. In the meantime, does the the patch below fix it? 

```
diff --git a/src/output.c b/src/output.c
index 437cb5c..bb0e42a 100644
--- a/src/output.c
+++ b/src/output.c
@@ -827,6 +827,8 @@ output_render(struct output *output, pixman_region32_t *damage)
 
 	render_layer_toplevel(output, damage,
 		&output->layers[ZWLR_LAYER_SHELL_V1_LAYER_OVERLAY]);
+	render_layer_popups(output, damage,
+		&output->layers[ZWLR_LAYER_SHELL_V1_LAYER_OVERLAY]);
 
 	if (output->server->input_mode == LAB_INPUT_STATE_MENU) {
 		render_menu(output, damage, server->rootmenu);
```

**Comment by LBCrion** [comment]
Yes, the above patch fixes the issue.

**Comment by johanmalm** [comment]
Nice one. Wish issues were that easy :smile:
Thanks for the help.
Nice bar by the way. Will play with it.

**Comment by 01micko** [comment]
> Nice one. Wish issues were that easy smile Thanks for the help. Nice bar by the way. Will play with it.

It is. Been playing a bit and am impressed.

**Comment by keshto** [comment]
Nice thanks you all

**Comment by clemencyworld1** [comment]
Please where and how do i apply the patch. Having the same issue. Though am on wayfire but it might work for me. The offending application is dropbox.

**Comment by johanmalm** [comment]
> Please where and how do i apply the patch. Having the same issue. Though am on wayfire but it might work for me. The offending application is dropbox.

It was this commit.
https://github.com/labwc/labwc/commit/588f2331511159b1b497a9e98792741bce41d7be

**Comment by LBCrion** [comment]
Is this the case of dropbox menu not correctly working with sfwbar and
wayfire? In this case would be better to open a PR for sfwbar. This issue
was labwc specific and didn't affect wayfire.
