### ISSUE TITLE
Keep dragging the scrollbar when leaving the surface

### ISSUE THREAD

**Issue by keshto** [labwc/labwc#241]
1. Open any window that has a scrollbar (sakura, firefox, etc)
2. Grab the scrollbar and move up/down
3. go outside of the window while still dragging
What happens:
- scrolling stops.
What should happen:
- scrolling should continue like in any other WM

**Comment by keshto** [comment]
If someone want to point me at where the potential problem would be I can poke around and see if I can address it.

**Comment by johanmalm** [comment]
Possibly here.
https://github.com/labwc/labwc/blob/68d897e1f5e23d5e9991468d9def7b7a570d084d/src/cursor.c#L312

**Comment by keshto** [comment]
Removing that else statement does keep the scrolling when cursor comes back over the client(window) so that is a start, but it still stops scrolling when the cursor is off the client. Most other windowmanagers (tabby, vivariaum, tinybox, dwl, etc) that are based on tinywl (and it as well) has this issue. Hikari and sway handle the cursor differently and don't have this issue.

**Comment by Consolatis** [comment]
> does keep the scrolling when cursor comes back over the client(window)

That is because we detect the view/window under the cursor on mouse movement.
We could store the current view on cursor button down and send the movement with adjusted coordinates to that surface when moving the cursor while the button is still held down. On release we would then reset the view.

It feels pretty hackish to me though.. I don't know if we actually \*want\* to do that.
When the cursor leaves the surface of a client it should not get any events from that cursor anymore until it moves over the surface again.

**Comment by keshto** [comment]
What happens when dragging something from one window to another?

Have the mouse down while outside of the window seems quite reasonable to me especially with the new trend of having micro scrollbars it is very easy to go out of the window while dragging the scrollbar. Personally does not seem hackish to me what you described. This is the behavior on sway, Watfire, and pretty much any window manager that is not based on tinywl
