### ISSUE TITLE
Focus issues when minimizing window

### ISSUE THREAD

**Issue by acoolstraw** [labwc/labwc#270]
I have 2 windows open: Chromium on top, and VS Code behind it. When I minimize Chromium and click on VS Code it just brings up Chromium and focuses on it. Alt+Tab works as expected, but sometimes I'd rather minimize a window than cycling between them

**Comment by Consolatis** [comment]
What branch / version of labwc are you using?

**Comment by acoolstraw** [comment]
Using `labwc` from the AUR, version 0.5.0. It does happen with `-c /dev/null` arguments

**Comment by Consolatis** [comment]
After some more discussion in IRC the issue seems to be related to minimizing any X11 application.
It seems to fail giving keyboard / mouse focus to the new top most client, thus further keyboard / mouse input ends up on the minimized application.

In the case of Chromium that in turn seems to cause it to send a request to the xwayland server to be focused / unminimized.

**Comment by Consolatis** [comment]
@acoolstraw would be great if you could test https://github.com/Consolatis/labwc/tree/fix/issue-270

**Comment by acoolstraw** [comment]
Works!
