### ISSUE TITLE
Switch configuration format to YAML, INI or TOML

### ISSUE THREAD

**Issue by avdb13** [labwc/labwc#295]
No explanation needed here. It's easy to miss a closing tag since XML is hard to read starting from +50LOC, there's a lot of nesting and it's even difficult to be parsed correctly by software itself. Can we please switch to something more user-friendly? The alternatives are brought up in the title.

**Comment by 01micko** [comment]
Please read https://github.com/labwc/labwc/issues/101

**Comment by acoolstraw** [comment]
JWM's config is one of the better uses of XML

**Comment by Consolatis** [comment]
`.ini` in particular actually sounds like a pretty bad fit: For mousebinds for example you have
- a context (like client-window, maximize button, ..)
- the button itself (left, right)
- optional keyboard modifier
- there may be multiple actions for a single mousebind, each of those in turn may have arguments

**Comment by acoolstraw** [comment]
maybe TOML? pretty capable and popular

**Comment by johanmalm** [comment]
See https://github.com/labwc/labwc-acceptance-criteria#32-configuration-syntax

I think it would be a pretty unattractive move for `labwc` to change config language for the following reasons:

(a) We chose an existing config+theme specification/format to be able to focus on creating a compositor rather than re-inventing stuff. In my view that hold true as much as it ever has; there is lots of work to stabilize this project. Developer time is precious, so we need to use it wisely.

(b) Supporting two config formats increases maintenance burden and complexity, and in my view is therefore a pretty bad idea.

(c) I think this is the wrong context to argue over the subtleties of different markup-languages because what we are doing is pretty simple and small-scale, so most arguments become irrelevant :smile:
[Is XML really that hard to read on this scale?](https://github.com/labwc/labwc/blob/master/docs/rc.xml)

(d) Software maintenance is important and unless libraries and widely supported you have to be prepared to statically link or create your own, which is just hard work and likely to significantly slow down the general progress of `labwc`. libxml2 is widely supported across OSs and distributions and is event part of [Linux Standard Base Common Libraries](https://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Common/LSB-Common/requirements.html#RLIBRARIES). I searched for TOML on some OSs/distros and found support relating to python, perl and rust, but not for C. 

(e) The simplicity of .ini is attractive, but like @Consolatis pointed out other consideration kick in which would probably just make quite clumsy and bespoke.
Also, it would seem a bit weird/inconsistent/confusing to keep `menu.xml` in XML and change `rc.xml` to `rc.ini`. We could of course use another menu format like that of `fluxbox` or [https://hellosystem.github.io/docs/developer/menu.html](https://hellosystem.github.io/docs/developer/menu.html)... but at this point I'm like REALLY??

So, anyway, it's good to discuss these things, but I just don't want to get anyone's hope up that we will be converting to TOML/YAML/whatever. Hope that okay. Will close with this.
