### ISSUE TITLE
labwc for Debian/Ubuntu

### ISSUE THREAD

**Issue by ConLenov** [labwc/labwc#301]
Will there be a deb - package for labwc? And will labwc be available in Debian/Ubuntu repositories?

**Comment by johanmalm** [comment]
I prefer not to include packaging files in this repo.

https://drewdevault.com/2021/09/27/Let-distros-do-their-job.html

**Comment by lidgnulinux** [comment]
> Will there be a deb - package for labwc? And will labwc be available in Debian/Ubuntu repositories?

Just compile it yourself, it's not that hard. I'm using debian BTW.

**Comment by acoolstraw** [comment]
It's 2 commands to compile it yourself, actually. Pretty easy!

**Comment by johanmalm** [comment]
On rolling distros it is very straight forward, but the challenge on Debian and Ubuntu can be that some dependencies are too old. Although I'm fairly confident in saying that if the system libraries meet the requirements of `wlroots`, then `labwc` should be fine to build.

I haven't tried building on Debian since before Buster, so can't really help. I ran on Ubuntu 20.04 LTS for a while, but soon had to manually install `wayland` and `wayland-protocols` which isn't advisable... it might break your system.

@lidgnulinux If you're willing to share any up-to-date instructions for installing on Debian that would be gratefully received. Updating the https://github.com/labwc/labwc/wiki/Build would be great as it's quite out of date.

https://github.com/swaywm/sway/wiki/Debian-10-(Buster)-Installation#install-wlroots refers to wlroots 0.10, so is also quite old.

@ConLenov Do reach out here or on IRC if you struggle to build.

**Comment by lidgnulinux** [comment]
@johanmalm, I did build labwc many times since 2020-ish till now, I just follow the documentation, satisfy the dependencies.

**Comment by 01micko** [comment]
This advice should hold true for any distro.

If you remove all old dependencies with the package manager and build new dependencies and install to the _default_ location (`/usr/local`) there shouldn't be any problems.

**Comment by Sunderland93** [comment]
I create PPA for Ubuntu 22.04 https://launchpad.net/~samoilov-lex/+archive/ubuntu/labwc

**Comment by johanmalm** [comment]
@Sunderland93 
Thanks. I've added to the wiki
https://github.com/labwc/labwc/wiki/Install#ubuntu
