### ISSUE TITLE
uninitialized 'resize_edges' when building with system wlroots

### ISSUE THREAD

**Issue by adcdam** [labwc/labwc#318]
i already have wlroots 0.15.1 and seatd installed why this is downloading and using a subproject?
how do i change the meson.build to use system wlroots and system seatd instead of  using the subproject?
im making the package for slackware.

**Comment by eli-schwartz** [comment]
This project depends on `['>=0.16.0', '<0.17.0']`

You can instruct Meson to error instead of downloading subprojects using `--wrap-mode=nodownload` as an option to `meson setup`.

I'm not really sure why, but... this project first looks up the subproject, then looks up the dependency, which means it doesn't respect `--force-fallback-for` or `--wrap-mode=forcefallback`, which would be the generally preferred method for system integration.

**Comment by adcdam** [comment]
how can depend on wlroots ['>=0.16.0', '<0.17.0'] ?
when it execute the subproject it download version 0.15.1
also the wrap file say revision 0.15.1
projects using git versions of wlroots are a nightmare depend on a version not already been released.

**Comment by Consolatis** [comment]
> projects using git versions of wlroots are a nightmare depend on a version not already been released.

Completely agree. labwc was somewhat recently ported to the newish scene-graph API of wlroots and that one isn't available in wlroots version 0.15 and AFAIK there is no official wlroots release yet which includes the scene-graph API. That is also one of the reasons why we added a "before scene-graph" branch called v0.5 that should work fine with wlroots 0.15.1.

Regarding the meson settings / system vs built-in I can't really comment because that is not really an area of expertise of mine.

The current master branch subproject points to a specific commit of wlroots master:
https://github.com/labwc/labwc/blob/master/subprojects/wlroots.wrap
and depends on `wlroots_version = ['>=0.16.0', '<0.17.0']`

Branch v0.5 subproject points to wlroots 0.15.1:
https://github.com/labwc/labwc/blob/v0.5/subprojects/wlroots.wrap
and depends on `wlroots_version = ['>=0.15.0', '<0.16.0']`

**Comment by adcdam** [comment]
thanks Consolatis well at least Branch V0.5 can work with wlroots 0.15.1, now what i need is that it use system wlroots and not the subproject.
i made the package a few minutes ago and it work but to be accepted in slackbuilds.org i need that the package use system wlroots and not download anything from git.
best regards

**Comment by johanmalm** [comment]
Thanks. We should possibly patch like this to ensure resize_edges is initialized:

```
diff --git a/src/cursor.c b/src/cursor.c
index 3f48283..21dd519 100644
--- a/src/cursor.c
+++ b/src/cursor.c
@@ -750,6 +750,7 @@ cursor_button(struct wl_listener *listener, void *data)
                return;
        }
 
+mousebindings:
        /* Determine closest resize edges in case action is Resize */
        resize_edges = ssd_resize_edges(view_area);
        if (!resize_edges) {
@@ -759,7 +760,6 @@ cursor_button(struct wl_listener *listener, void *data)
                        ? WLR_EDGE_TOP : WLR_EDGE_BOTTOM;
        }
 
-mousebindings:
        if (event->state == WLR_BUTTON_RELEASED) {
                triggered_frame_binding |= handle_release_mousebinding(view,
                        server, event->button, modifiers,
```

@Consolatis any thoughts. I'll have a review/think later this week.

Regarding the `meson.build`, thank you for this feedback. I hadn't noticed that it downloads `wlroots/` even if the right version is installed on the system. That's a bit annoying and should be sorted. I'm not sure how to be best fix it. I welcome help if possible. Otherwise I'll investigate later in the week.

**Comment by eli-schwartz** [comment]
> I'm not sure how to be best fix it. I welcome help if possible. Otherwise I'll investigate later in the week.

Speaking with my Meson core dev hat on -- I know this one. :) Here, have a fix.

**Comment by adcdam** [comment]
@johanmalm i tried the patch but it say :
```
patching file src/cursor.c
Hunk #1 FAILED at 750.
Hunk #2 FAILED at 759.
2 out of 2 hunks FAILED -- saving rejects to file src/cursor.c.rej

```

**Comment by Consolatis** [comment]
@adcdam
> warning: uninitialized 'resize_edges' may be used in this function

I don't see any build warning like that here (neither for clang nor gcc):
https://github.com/labwc/labwc/pull/322/checks

And I don't see that warning locally either.

Regarding packaging labwc v0.5 for slack: I'd recommend waiting for @johanmalm to do a minor 0.5.2 release that would then include the system wlroots dep fix from @eli-schwartz.

**Comment by adcdam** [comment]
thanks a lot, ill wait for the 0.5.2 release!
best regards!!
