### ISSUE TITLE
Restore geometry when moving window with the mouse away from window snapping

### ISSUE THREAD

**Issue by Flrian** [labwc/labwc#391]
Similar to what already happens with maximized windows, but also for SnapToEdge and ideally for whatever gets implemented in the future (https://github.com/labwc/labwc/issues/386).

**Comment by Consolatis** [comment]
I think its a good feature.

Some random thoughts about how to implement it.
For this we can't use `view->unmaximized_geometry` at all. Reason:
- if we don't have an additional `is_tiled` boolean: when maximizing a tiled window it would get overwritten with the tiled dimensions, thus on following unmaximize it would only get back to the tiled state and when then moving the window away from that tiled state we wouldn't know the original geometry anymore.
- if we add an additional `view->is_tiled` boolean and thus not overwrite `view->unmaximized_geometry` we would restore to the untiled state on unmaximize instead of the tiled state and wouldn't have any idea what the tiled dimensions of this view was.

So I'd think we need another `wlr_box` like `view->untiled_geometry` and possible an `view->is_tiled` boolean as well so we don't have to check if the box is empty.
