### ISSUE TITLE
[Feature Request] Workspaces

### ISSUE THREAD

**Issue by hobdob** [labwc/labwc#40]
Last time I used labwc, resizing feels a bit finicky doing it from corners of a window. It would be nice to have a function to use Alt+Right mouse button to resize it anywhere within the window and Alt+Left mouse button for moving a window.

Is it out of the scope to support both of these features?

**Comment by johanmalm** [comment]
This is a nice features. I've based "resize_edges" on which quadrant the cursor is in, for example top/left, top/right, and so on.
Let me know if it's not what you had in mind.

**Comment by plr20** [comment]
Thanks, tested it works exactly like in Openbox. Sorry that I keep mentioning it but any chance for workspaces if it is in the projects scope?

**Comment by johanmalm** [comment]
Sorry - didn't read the title properly.
Let me play with workspaces in openbox a bit before deciding.
I never use them myself, so struggle to think through what to implement.
What happens if you have a multi-output setup? Are workspaces linked to outputs or does one workspace cover all outputs?

**Comment by plr20** [comment]
> one workspace cover all outputs

I think this is the case if I remember correctly.

**Comment by Narrat** [comment]
It works that way.
Although there were patches around which changed that behaviour. For example openbox-multihead
https://bbs.archlinux.org/viewtopic.php?id=124331

**Comment by jstrunk** [comment]
> > one workspace cover all outputs
> 
> I think this is the case if I remember correctly.

That is how it works due to X11 limitations. Workspaces should be independent of outputs. I like the way Mac OS handles them. You can have a dynamic number of workspaces for each output and move workspaces between outputs if needed.

When I give presentations and demos, I like to have the libre office presenter mode with my notes, the video conference window, and other things I won't share in different workspaces on one output and the presentation and any browser or code windows in different workspaces on the other output. That way I can share the screen of the presentation/demo output and quickly switch workspaces to show different things. I can also switch workspaces on the other output without my audience noticing.

**Comment by Soundtoxin** [comment]
You can also look at i3/Sway to see one way to handle workspaces. They're created when you go to them and they're per-display, so workspace 3 may be on your left monitor and 4 on your right monitor, and you can optionally move the whole workspace to the other monitor. This also lets you focus a workspace number that's on the other monitor to still jump to it easily.
I recall awesomewm handling them another way, where I think both monitors get workspaces 1-9 or so and you have to change monitor focus if you want to get to one of the ones on the other monitor. It also differs in that all the workspaces are showing in the panel by default, whereas i3/Sway only show workspaces that have stuff in them.

**Comment by notthewave** [comment]
It might be nice to have tags instead of workspaces. They're a little more flexible. With tags, it is possible to assign a window to multiple workspaces, this comes in handy when you need to some research. But tbh this is only really great when you can have a window always on top.

**Comment by johanmalm** [comment]
Thanks for all the views. Just wanted to put a 'holding-position' on this.

I want to focus on completing all the Cat A items of the Acceptance Criteria first (of which this is not one) as well as focusing on stability and implementing `wlr_scene`.

However, I do think it's a feature that ought to be implemented at some point, so will keep the issue open to develop the details.

I'm sure workspaces would be implemented with a quick hack, but I will resist temptation and do it properly later.

**Comment by FriederHannenheim** [comment]
If you add them please make it possible to have either global keybinds to switch workspaces or per-screen keybinds. It would be great to push super + 2 to go on workspace 2 on the monitor the mouse is on and then go to the other monitor and press super + 2 there to go to workspace 2 there. I don't like the way sway has implemented this where you can only have one workspace per keybind which is bound to one monitor.

**Comment by Soundtoxin** [comment]
> If you add them please make it possible to have either global keybinds to switch workspaces or per-screen keybinds. It would be great to push super + 2 to go on workspace 2 on the monitor the mouse is on and then go to the other monitor and press super + 2 there to go to workspace 2 there. I don't like the way sway has implemented this where you can only have one workspace per keybind which is bound to one monitor.

That makes it harder to get to workspaces on the other monitor... Not the end of the world, but worth noting. Also, you can add new workspaces with arbitrary names as well as keybinds for those newly-named workspaces if you don't like the Sway defaults. I'm not sure if you could have keybinds that work per-monitor, though. You might need a whole second set. You could use prev/next workspace keybinds to get around per-monitor if you don't have a lot of workspaces.

**Comment by acoolstraw** [comment]
It'd be quite nice to have workspaces (or tags, those seem nice too), they're a very good way to be efficient especially when dealing with limited screen space, and want some organization.

**Comment by Consolatis** [comment]
[We implemented workspaces](https://github.com/labwc/labwc/pull/333) in their simplest form which also matches the idea of labwc:
- a workspace covers all outputs
- a window can only be in a single workspace at any given time (no tags)
- only windows of the current workspace show up in the `A-Tab` OSD
- in a default configuration this feature should be completely invisible
- a panel will show all windows from all workspaces and when activating a window with a panel the workspace will be switched automatically because [the respective wayland protocol is still work in progress](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/40).
