### ISSUE TITLE
Bugs when tiling/dragging directly from fullscreen.

### ISSUE THREAD

**Issue by Flrian** [labwc/labwc#404]
Not sure why anyone would ever actually do this, but I thought I should mention it.

If I tile/SnapToEdge or drag directly out of fullscreen mode it works, but the app never actually seems to exit the fullscreen state.
Most obvious in Firefox because it doesn't change out of fullscreen ui (See no address bar when not hovering over it). [Screenshot](https://user-images.githubusercontent.com/4444593/174477241-e98053fb-fce7-48f0-bdc9-1414aae8e447.jpg)

Sometimes when doing this resizing doesn't work, sometimes it does? Maximize never seems to work.

When doing this with a window that started maximized the titlebar seems.. screwed, especially when dragging with the mouse? (https://github.com/labwc/labwc/issues/403 maybe related) [Screenshot](https://user-images.githubusercontent.com/4444593/174477342-bab23db7-24f9-4c0c-8e5f-c894e5b2eeba.jpg)

**Comment by acoolstraw** [comment]
oh yeah. if I maximize Chromium and then tile it, I can't resize it, I need to unmaximize it first and then I can do that. slightly bothersome.

**Comment by Consolatis** [comment]
@acoolstraw that should be fixed in #401 
With that
- tiling now automatically exists maximized state
- resizing in tiled state exists tile state (an thus also invalidates whatever dimensions were store before tiling)

Regarding fullscreen + tiling:
> Not sure why anyone would ever actually do this, but I thought I should mention it.

Thinking about just removing the ability to tile from fullscreen state, guess same could be done for move and resize.

**Comment by Consolatis** [comment]
Latest mater disables `SnapToEdge` when in fullscreen.
