### ISSUE TITLE
Binding by keycode instead of keysym

### ISSUE THREAD

**Issue by alandiwix** [labwc/labwc#446]
Is there any way to bind actions to keycode instead of keysym? If not, it would be really nice to have.

**Comment by Consolatis** [comment]
Related:
- #351
- #365
- #370

This is not exactly my area of expertise so take the following with a grain of salt.

Especially #365 might provide a workaround (Using e.g. `0x21`).
We should likely clean up those issues a bit and figure out a way to go forward, either by documenting the feature or by providing a proper way to create keybinds like `S-!`.

**Comment by Arnaudv6** [comment]
Title should be 'Binding by keycode as an alternative to keysym'.
Stating the obvious, but _most_people®_ do the opposite and want bindings to adapt with layouts.

**Comment by Consolatis** [comment]
Should be fixed by
- #997

Note: the workaround keybinds will have preference over raw ones, e.g. `W-S-0x21` would get used if defined and `W-S-1` would not be used at all. Thus suggesting to replace all workaround keybinds with proper ones. Feel free to open a new issue if there are any further issues with the keybinds.

@Arnaudv6
> Title should be 'Binding by keycode as an alternative to keysym'.
> Stating the obvious, but _most_people®_ do the opposite and want bindings to adapt with layouts.

This should still work using the `W-S-0x21` / `W-S-exclam` variant instead of `W-S-1` for those specific keys which include the shift modifier. Labwc still prefers the layout ones and only falls back to raw ones if no layout based binding had been found.
