### ISSUE TITLE
Static window ordering mode

### ISSUE THREAD

**Issue by alandiwix** [labwc/labwc#450]
NextWindow moves the selected window to the top of the list. AFAIK this is pretty common patters for Alt-Tab in most "mouse-driven" compositors/wms, so that's not a bug.

Would it be possible to avoid this behaviour with some flag in config though? Static list can be much more intuitive to navigate in.

**Comment by johanmalm** [comment]
I don't understand the proposal.
The selected window is already at the "top" of the list isn't it?
What do you mean by "static list".
Could you give an example to help me understand.

**Comment by alandiwix** [comment]
@johanmalm The suggestion is actually about the opposite, so selected window would stay on it's position in the list and the order of the windows would stay the same.

Right now:
1. You spawn 4 windows.
2. Windows are in this order: **1**, 2, 3, 4.
3. You select window 3.
4. Windows are in this order: **3**, 1, 2, 4 - next window is 1 and previous is 4.

The mode in suggestion would be:
1. You spawn 4 windows.
2. Windows are in this order: **1**, 2, 3, 4.
3. You select window 3.
4. Windows are in this order: 1, 2, **3**, 4 - next window is 4 and previous is 2.

**Comment by johanmalm** [comment]
Yes. Agree. Adding flags to the ordering of server->view would probably be quite deep.

I’m not around a linux box for a while, but could this not be achieved with a foreign-toplevel client?

**Comment by Consolatis** [comment]
> could this not be achieved with a foreign-toplevel client?

If the foreign-toplevel client keeps using the same wayland connection, yes: it could simply sort by wayland object ids).

If it reconnects (e.g. use-cases like `wlctrl` for X11) it can't do that deterministically because the wayland object IDs for a toplevel are only valid throughout the lifetime of the connection. After reconnecting you might have
1) completely different object IDs
2) some toplevel reuse an object ID from a another toplevel you got from the earlier connection

It is something I ran into while playing around with [`wlctrl`](https://github.com/Consolatis/wl_framework/blob/main/examples/wlctrl.py#L125).

**Comment by Consolatis** [comment]
Closing this for now as its unlikely we implement the feature.
