### ISSUE TITLE
Some applications don't have app_id

### ISSUE THREAD

**Issue by 01micko** [labwc/labwc#460]
As the title says. Two notable ones are Vivaldi ([they don't seem too interested](https://forum.vivaldi.net/topic/75556/vivaldi-on-native-wayland-not-showing-app_id)) and Opera browsers. I'm sure there would be others. I thought about writing a wrapper that creates an `app_id` but that is wrong on many levels.

A possible fix could be this [weston](https://gitlab.freedesktop.org/wayland/weston/-/merge_requests/611/diffs?commit_id=2e7dd899b0b6dcaf1248f29c9920ef7baedeaf08) fix.

Thoughts?

**Comment by Consolatis** [comment]
Interesting. Thanks for bringing this up.

**Comment by Consolatis** [comment]
So weston seems to use the title as fallback for the app_id. I am not really a fan of this solution because it really doesn't help much with the original issue of a panel being unable to figure out the correct `.desktop` file / icon.

I think a cleaner solution would be to implement [application policies](https://github.com/labwc/labwc/issues/203#issuecomment-1185873621) and provide an option there to overwrite the app_id.
So it would match based on title (something like `^Vivaldi`) and then use the user-defined app_id `vivaldi`.

**Comment by LBCrion** [comment]
Can labwc use a pid to get an executable name and use that as an app_id? That may be a cleaner fallback.

**Comment by Joshua-Ashton** [comment]
What is app_id used for?

**Comment by 01micko** [comment]
In `labwc` OSD, in `sfwbar` taskbar icons... just exposes the name of the app to the compositor. Most GTK and QT apps handle this. It's part of the  [xdg-shell](https://cgit.freedesktop.org/wayland/wayland-protocols/tree/stable/xdg-shell/xdg-shell.xml) protocol. Also gives hints to `dbus` </simple explanation>

**Comment by Consolatis** [comment]
> Can labwc use a pid to get an executable name and use that as an app_id? That may be a cleaner fallback.

That might also be an option, but may be really complex to implement correctly:
- there are PID namespaces
- the executable (`exe`, `comm`) might be an interpreter like `Python`, `bash` or `node`
- so we might have to fall back to `cmdline` at which point it gets really nasty to parse
- there might be more details that we have to get right

I am not sure if these added complexities for labwc outweigh the benefits for the 2 1/2 apps that refuse to follow the xdg-shell specs. The application policy framework for labwc on the other side is something that we'll add at one point anyway so that would be relatively easy to extend to also overwrite the app_id.

There is no time-frame for the implementation though and there are other compositors which don't modify the app_id (or actually make it harder to detect, e.g. weston). For this reason panels should likely add their own app_id -> `.desktop` file / icon fallback anyway.

**Comment by 01micko** [comment]
This issue is solved in `sfwbar` so probably no need to fix it here. See https://github.com/LBCrion/sfwbar/commit/a0c10d2fdd232f3daa6b5430eaf304e0f44290b9
