### ISSUE TITLE
Change default of A-F3 to "bemenu-run -n"

### ISSUE THREAD

**Issue by datMaffin** [labwc/labwc#474]
I would recommend to change the `bemenu-run` run command to  `bemenu-run -n` to avoid the issue of overlapping UI.
In my case bemenu decided to spawn beneath waybar. I therefore feel like adding the `-n` switch will result in better default behavior.

Code: https://github.com/labwc/labwc/blob/32b176e05e0b7898028006123bfe1dad6d9b1082/src/config/rcxml.c#L506

Related: https://github.com/Cloudef/bemenu/issues/134

**Comment by Consolatis** [comment]
Thanks for bringing this up. Personally I don't even have bemenu installed so can't test anything but created [a PR](https://github.com/labwc/labwc/pull/479) for others to test / accept.

**Comment by johanmalm** [comment]
It is strange that bemenu is rendering behind waybar. The layer-surface created last should render on top (within each layer) because of how the nodes are added. Or am I missing something? Do we have to do a manual `wlr_scene_node_raise_to_top()` after creating  a new layer-surface?

Please could you confirm that:
- you start bemenu after waybar
- you run waybar in either `bottom` or `top` layer

I use both waybar and bemenu. With `bemenu-run` I get this:

![20220811_15h56m46s_grim](https://user-images.githubusercontent.com/6955353/184167208-8541b8b3-26df-4c6f-963d-ab4b0b49d6fa.png)

With `bemenu-run -n` I get:

![20220811_15h57m24s_grim](https://user-images.githubusercontent.com/6955353/184167349-71b0cfb8-8b6a-4274-bdab-5a114aa0fd4d.png)

I prefer the former, but am keen to understand if we have a problem with node z-order.

**Comment by datMaffin** [comment]
Äähmm.. 

I just tested it again on the latest version packaged in the Distro and from master.

It looks like this is no longer an issue on the master! Sorry.

Master:
![image](https://user-images.githubusercontent.com/29998721/184180138-8fd0110d-6965-478b-ae94-2e9915557d84.png)

**Comment by Consolatis** [comment]
Thanks for verifying :)

Closing this as requested.
