### ISSUE TITLE
[feature request] support libinput send events mode

### ISSUE THREAD

**Issue by johanmalm** [labwc/labwc#559]
...to enable/disable input devices

https://wayland.freedesktop.org/libinput/doc/latest/configuration.html#send-events-mode

**Comment by Sachin-Bhat** [comment]
Hello! If this issue is still open, may I work on it? It would give me a nice opportunity to learn about libinput while I am at it;)
If possible, I would like to walk you through my thought process on going about this issue.
1. Modify the `libinput_category` struct in `config/libinput.h` to include a new variable for the send events mode.
2. Update the `libinput_category_init()` function in `src/config/libinput.c` to initialize the `send_events_mode` variable.
3. Modify any relevant functions or code sections that handle libinput configuration to include the `send_events_mode` variable. For example, we may need to update the `libinput_category_create()` function to set the default value for `send_events_mode`.
4. We may need to update other relevant sections to handle libinput `send_events_node` configuration. My guess is `include/config/rcxml.h` and `src/config/rcxml.c` though I am a little unsure of the details. Some guidance here would be nice!

Also, please let me know if something is missing. Suggestions for a better approach are also welcome:)

**Comment by johanmalm** [comment]
That would be great. Someone asked about enabling/disabling inputs the other day and I had forgotten about this one :smile:

When processing node names in rcxml.c we would have to consider what values we want to accept. I haven’t looked, but I suspect it would be more than true/false.

**Comment by Sachin-Bhat** [comment]
> When processing node names in rcxml.c we would have to consider what values we want to accept. I haven’t looked, but I suspect it would be more than true/false.

It is indeed more than true and false. It has to be an enum since there are three possible values/states.

I am just waiting on my PR (#956) to be accepted in the meantime:)
