### ISSUE TITLE
wlroots MR#3740 appears to have caused problems with window titles

### ISSUE THREAD

**Issue by kode54** [labwc/labwc#587]
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3740

This MR appears to be causing damage issues with window titles. The result is that window titles never repaint from their initial contents, only stretch or shrink to fit the size of whatever the current title is.
![2022-10-13_16:52:21](https://user-images.githubusercontent.com/796316/195831996-8254f0cf-a50f-46bf-958d-dc0069f6ec05.png)

**Comment by Consolatis** [comment]
It seems something is indeed wrong with latest wlroots.
- I am unable to change the foot title via `printf "%s" "$(tput tsl)title$(tput fsl)"`
- The autoscaling title buffer still updates, caches and does `wlr_scene_buffer_set_buffer()` internally but it doesn't seem to update on screen which results in blurry titles on scaled outputs.

So it seems setting a new buffer via `wlr_scene_buffer_set_buffer()` fails once its initially set.
@Nefsen402 ideas?

@kode54 
You could likely work around it by just using the last tested wlroots version via `meson configure --force-fallback-for=wlroots build` to use a subproject instead of using your system wide `wlroots-git` installation.

**Comment by Nefsen402** [comment]
@Consolatis This is a bug in labwc. Labwc shouldn't be modifying the contents of the buffer while the scene is using it. Scenes will not ignore any call to set_buffer if what buffer its given is the same. Since compositors aren't allowed to modify while it's using, this conditional is correct. The fix is to either double buffer (wastes memory) or when you want to rerender the buffer call `wlr_scene_set_buffer(scene_buffer, NULL)` to tell scenes that it can no longer us this buffer, modify it and give it back to scenes. This will probably work, but it isn't perfect because it's possible that the buffer region might show black while re-rendering a buffer (this won't be a problem because compositors don't have asynchronous code). The true and correct fix to this is to wait for [wlr_raster](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3634).

**Comment by Nefsen402** [comment]
What you actually probably want to do is follow what https://github.com/swaywm/sway/pull/6844/commits/182d1e9173deb1cdd3621d32964846e5ec1b951a does. In this code, while scenes is using the old buffer, a new buffer is being constructed in an entirely new buffer. Things aren't double buffers per se because we aren't keeping around two copies of a buffer all the time. We're just making an entirely new one in place. Things could be further optimized with wlr_raster.

**Comment by Nefsen402** [comment]
For those following along at home, this is the problematic if statement: https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/types/scene/wlr_scene.c#L562

**Comment by Consolatis** [comment]
> Labwc shouldn't be modifying the contents of the buffer while the scene is using it.

We are not doing that at all AFAIK.

> Scenes will now (as a result of the blamed MR) ignore any call to set_buffer if what buffer its given is the same.

Its a new instance of a wlr_buffer implementation, they are always read-only and never changed but instead replaced with a new one.

**Comment by Nefsen402** [comment]
> We are not doing that at all AFAIK.

Hmm, it seems that's actually the case.

 [Take a look at this code](https://github.com/labwc/labwc/blob/d424514e24bbee1c32b19c9192a065c18c9e7fe5/src/common/scaled_scene_buffer.c#L58). This is dubious: If we get a cache hit, it doesn't reset the buffers dest size. This is in line with what I see in the screenshot where the text is completely stretched over a large part of the screen. I would advise to completely drop the cache, sway keeps it simple and regenerates a buffer if there is a scale change or whatever, this works fine even with the wlroots mentioned MR.

At any rate, I'm unable to see an issue with the wlroots code after double checking it.

**Comment by Consolatis** [comment]
Thanks for taking your time into looking at this. Will keep debugging a bit more.

**Comment by Consolatis** [comment]
Should be fixed upstream.

@kode54 updating wlroots-git should solve the issue.

@Nefsen402 thanks again for the prompt fix.
