### ISSUE TITLE
Void-musl CI has outdated wayland-protocols 1.26 < 1.27

### ISSUE THREAD

**Issue by bi4k8** [labwc/labwc#615]
Recent Void-musl CI log: https://github.com/labwc/labwc/actions/runs/3429663690/jobs/5715585939
```
wlroots| Dependency wayland-protocols found: NO found 1.26 but need: '>=1.27'
wlroots| Run-time dependency wayland-protocols found: NO (tried pkgconfig and cmake)
wlroots| Looking for a fallback subproject for the dependency wayland-protocols

subprojects/wlroots/protocol/meson.build:1:0: ERROR: Neither a subproject directory nor a wayland-protocols.wrap file was found.
```

This is probably fallout from #575, and may at some point resolve itself, but I figure we should track our broken CI until we or upstream fix it.

**Comment by Consolatis** [comment]
Its actually fallout from #606 which increased the wlroots version that in turn increased the required wayland-protocols version.

Void uses GH for their packages: https://github.com/void-linux/void-packages

If somebody feels like it they could open an issue or [even a PR](https://github.com/void-linux/void-packages/pull/35276) there to update to the latest version of wayland-protocols. I can't really test anything regarding Void Linux myself because my daily driver (aarch64 system) is pretty restricted in terms of memory so VMs are not really an option for me.

**Comment by bi4k8** [comment]
Seems to be working now.
