### ISSUE TITLE
Natural geometry not saved correctly after SnapToEdge+Maximize

### ISSUE THREAD

**Issue by jlindgren90** [labwc/labwc#633]
Steps to reproduce:
- Start with a normal (untiled, unmaximized) window in a given position
- Drag the window via titlebar to a screen edge until it snaps
- Drag the window via titlebar to a screen top until it maximizes
- Unmaximize the window

Expected results:
The window should return to the original position.

Actual results:
The window ends up in the top-left corner of the screen.

This has to do with the (somewhat sketchy) way `view->natural_geometry` is manipulated in `interactive_begin()/interactive_end()`. I have some ideas for a fix, and will submit a merge request when it's ready.

**Comment by Consolatis** [comment]
Hm.. That UX pattern is a bit strange because it differs from using doubleclick / a keybind for maximize when already in tiled mode. What should happen is that un-maximizing the window returns to the tiled state and if then moving the tiled window it should return to the original state (before tiling).

I am not sure if it makes sense to check for that in interactive begin to have the same behavior when dragging the window to maximize and then in interactive_end reset the tiling state. That adds yet more complexity but would be more coherent with the doubleclick / keybind method of maximizing.

**Comment by jlindgren90** [comment]
> That adds yet more complexity but would be more coherent with the doubleclick / keybind method of maximizing.

Hmm, yes, that would be more consistent. Currently `interactive_begin()` just clears the tiled state regardless. Maybe we could clear it in `interactive_end()` instead.

I think the changes in #634 would still be applicable whatever we do with the tiled state.

**Comment by jlindgren90** [comment]
I updated #634 so that un-maximizing the window returns to the tiled state.
