### ISSUE TITLE
Keyboard interactivity conflict between overlay and top layer-shell surface

### ISSUE THREAD

**Issue by Tamaranch** [labwc/labwc#668]
Labwc git master

If a layer-shell surface is on the overlay layer with keyboard interactivity set to on-demand, and another layer-shell surface appears on the top layer with keyboard interactivity set to exclusive, it does not get keyboard access.

This doesn't seem to me to be what is expected, although the spec can perhaps be interpreted that way. Wayfire does give exclusive keyboard access to the surface on the top layer.

Especially if the new surface has keyboard interactivity set to on-demand it will not get keyboard access either. Wayfire seems to have this behavior, which seems quite intuitive to me: if the last surface clicked before the new surface appears is on the overlay layer, then it keeps keyboard access, otherwise the new surface takes it.

**Comment by johanmalm** [comment]
I've had a quick look, and am left slightly unsure :smile:

1. At a glance, I think `labwc` follows the protocol more closely than `wayfire` in that it handles top + overlay (above views) as a special case. The `labwc` handling of keyboard interactivity is almost identical to that of `sway`.
https://github.com/labwc/labwc/blob/7ad5490ff00696f898d57fd78dbf7c28b58bc78c/src/layers.c#L74-L103
https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/protocol/wlr-layer-shell-unstable-v1.xml#L230-236

2. Playing around with `gtk-layer-demo` I realised that `labwc` does not handle layer-change (whoops), so you have to start the client in the layer you want it to be rather than changing it later. Whilst that is a separate issue (enhancement) it might have manifested itself in what you described - which was indeed the case for me when trying to reproduce the OP. When starting one client in top-layer and another in overlay-layer I can indeed move the keyboard access around regardless of on-demand and exclusive.

3. Is there a particular use-case you're exploring? The protocol does leave various aspects to the compositor implementation, so happy to experiment and change to suit.

4. If you run `labwc` nested and add the following to your `rc.xml` you can print a nice debug log of what's in each layer help understand layer-related issues.

```xml
    <keybind key="A-F11">
      <action name="Debug"/>
    </keybind>
```

Example output:

```
                                            X     Y        Node
                                         ----  ----  ----------------
 server->scene                              0     0  [0x562f1fd0a400]
   +-- layer-background                     0     0  [0x562f1fd34210]
      +-- tree                              0     0  [0x562f20068050]
         +-- tree                           0     0  [0x562f20042ee0]
            +-- surface                     0     0  [0x562f20066d20]
   +-- layer-bottom                         0     0  [0x562f1fd3b8d0]
   +-- server->view_tree                    0     0  [0x562f1fd0ba10]
      +-- workspace                         0     0  [0x562f1fd0bbd0]
         +-- view                         319   134  [0x562f200f8ad0]
            +-- view->ssd                 319   134  [0x562f20107370]
                   <skipping children>
            +-- view->scene_node          319   134  [0x562f200ff700]
               +-- tree                   319   134  [0x562f200f8c60]
                  +-- surface             319   134  [0x562f201061f0]
         +-- view                         319   134  [0x562f2012a080]
            +-- view->ssd                 319   134  [0x562f200fd6b0]
                   <skipping children>
            +-- view->scene_node          319   134  [0x562f201234e0]
               +-- tree                   319   134  [0x562f20121f60]
                  +-- surface             319   134  [0x562f201320e0]
      +-- workspace                         0     0  [0x562f1fd0bc40]
   +-- server->view_tree_always_on_top      0     0  [0x562f1fd0ba80]
   +-- server->unmanaged_tree               0     0  [0x562f1fd0baf0]
   +-- server->menu_tree                    0     0  [0x562f1fd0bb60]
          <skipping children>
   +-- tree                                 0     0  [0x562f1fd0d780]
   +-- output->osd_tree                     0     0  [0x562f1fd2c790]
   +-- layer-top                            0     0  [0x562f1fd2c430]
      +-- tree                              0     0  [0x562f1ffc3d80]
         +-- tree                           0     0  [0x562f20044190]
            +-- surface                     0     0  [0x562f1ff18d60]
      +-- tree                              0    30  [0x562f2011a4e0]
         +-- tree                           0    30  [0x562f2010f1e0]
            +-- surface                     0    30  [0x562f20122390]
   +-- layer-overlay                        0     0  [0x562f1fd2c550]
      +-- tree                            500   246  [0x562f20140390]
         +-- tree                         500   246  [0x562f20128140]
            +-- surface                   500   246  [0x562f20153a40]
   +-- tree                               500   246  [0x562f1fd2c670]
```

**Comment by Tamaranch** [comment]
I solved my problem for now by switching the window asking for exclusive keyboard access to overlay. But here is my use case, which is probably doubly out of scope :)
* On the one hand, I use layer-shell windows and D-Bus to reproduce the GtkSocket-GtkPlug scheme on which xfce4-panel's external plugins are based on X11 (see [this mail](https://mail.xfce.org/pipermail/xfce4-dev/2022-October/033092.html) for more details if desired). And I put these "layer-shell plugs" on the overlay layer for simplicity, to make sure they don't end up under the panel.
* On the other hand, I also use, at least potentially, layer-shell windows as popup windows. The only case for now is the clock calendar, but external plugins might use it later, like the WhiskerMenu. I tried with popovers, but they work really bad in GTK 3, otherwise I would have used them.

So in the end I could have the panel in top layer and keyboard on-demand, external plugins in overlay and keyboard on-demand, and a popup in top layer and keyboard exclusive. It's this popup (the calendar) that I also put in overlay so that it gets the keyboard when it opens.

**Comment by johanmalm** [comment]
Very interesting. I'll have a play with xfce-plugins to learn some more on this.
Could you point me to the xfce4-panel code where you handle the IPC alternative to GtkSocket/Plug?

I did notice that the panel is in `overlay` because it stops bemenu from becoming keyboard exclusive (which is part of this issue).

I think we've got some work to do in `src/layers.c`. In the move to the wlroots scene-graph API, this was left a bit messy (by me :blush). 

For example, I tried swapping the order in which keyboard-exclusive surfaces within a layer are given focus - but it doesn't seem to change anything! I'm not sure what's going on there, but will investigate.

https://github.com/labwc/labwc/blob/e4aa7cef765a81a6911839de16644eceeb2fb5e9/src/layers.c#L83

We also don't handle surface-map properly, so work to be done.

Why does the keyboard-interactivity for the panel itself need to be set to exclusive?

**Comment by Tamaranch** [comment]
> Could you point me to the xfce4-panel code where you handle the IPC alternative to GtkSocket/Plug?

Socket side:
* https://gitlab.xfce.org/Tamaranch/xfce4-panel/-/blob/wayland-xfw/panel/panel-plugin-external-wrapper-infos.xml
* https://gitlab.xfce.org/Tamaranch/xfce4-panel/-/blob/wayland-xfw/panel/panel-plugin-external-wrapper-wayland.c

Plug side:
* https://gitlab.xfce.org/Tamaranch/xfce4-panel/-/blob/wayland-xfw/wrapper/wrapper-external-infos.xml
* https://gitlab.xfce.org/Tamaranch/xfce4-panel/-/blob/wayland-xfw/wrapper/wrapper-plug-wayland.c

The wrapper/external naming gets a little confusing sometimes but it's legacy and I didn't want to change everything. I tried to be more or less consistent at least.

> Why does the keyboard-interactivity for the panel itself need to be set to exclusive?

It's not for the panel itself, which is only on-demand (as well as the external plugins), it's for the layer-shell popup (the calendar). It's to make sure you can typically hide it by pressing Esc right after opening it.

**Comment by Tamaranch** [comment]
> Playing around with `gtk-layer-demo` I realised that `labwc` does not handle layer-change (whoops), so you have to start the client in the layer you want it to be rather than changing it later.

You can force the layer change to be taken into account by remapping the surface apparently (hide/show via GTK in my case), as I have a fix for https://github.com/labwc/labwc/issues/661#issuecomment-1345619227 locally that makes external plugins switch from overlay to top when a toplevel goes fullscreen. And I can make it work on Labwc by remapping the plugin (it works without it on Wayfire).

**Comment by Consolatis** [comment]
I am currently trying to clean up some issues, what is the current state here?

AFAIR @johanmalm did partly rewrite and improve the whole keyboard handling for layer surfaces.

**Comment by johanmalm** [comment]
Done
