### ISSUE TITLE
Is there any way to query the compositor for information, similar to swaymsg?

### ISSUE THREAD

**Issue by winteriscariot** [labwc/labwc#679]
I really like labwc and i may eventually move to it, but for now `swaymsg` is a killer feature for sway that really keeps me there.

is there anything roughly equivalent for labwc? maybe not something as fully featured as swaymsg, but perhaps a way to at least query labwc for a list of windows?

**Comment by Consolatis** [comment]
> is there anything roughly equivalent for labwc?

Labwc is on the stand that custom IPC solutions like that (and to the same extent private wayland protocols) create unnecessary fragmentation and in the long run hinder wayland adoption because there is less desire to standardize the use-cases in formal wayland protocols that work everywhere.

> but perhaps a way to at least query labwc for a list of windows?

Labwc implements the wlr-foreign-toplevel protocol which is used by [various panels](https://github.com/labwc/labwc#6-integration) to query the list of windows (and minimize, maximize, activate them). Some alternatives:
- wlroots [example application](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/examples/foreign-toplevel.c)
- base Python [example application](https://github.com/Consolatis/wl_framework/blob/main/examples/wlctrl.py) (shameless self-plug)
- https://git.sr.ht/~brocellous/wlrctl
