### ISSUE TITLE
Element (Electron based) not showing decorations when CSD is enabled in rc.xml

### ISSUE THREAD

**Issue by umksan** [labwc/labwc#831]
Certain programs like Element, MPV and PPSSPP (all of them wayland native) don't show any decorations when CSD is enabled. (`<core><decoration>client</decoration></core>`)

I managed to "fix" it with a -really- nasty hack in `xdg-deco.c` ; it works but could bring other problems I believe. Here's the patch: https://github.com/umksan/labwc/commit/47f4b67f2c0b01d921e39e6ddd07d5b10b128fd9

Since Element uses Electron I have tried using `--enable-features=WaylandWindowDecorations` but decorations didn't appear either.

On the other hand, a retro gaming client Fightcade (which uses Electron but runs on Xwayland) is able to show SSD while CSD is enabled in rc.xml.

----

Thanks to @Consolatis for helping me to debug behaviour correctly. I tested multiple programs. All of them wayland native.

MPV and Element return this:

```
00:01:56.256 [../src/xdg-deco.c:31] Client requested server decorations
00:01:56.256 [../src/xdg-deco.c:39] We set decorations to server
```

PPSSPP:

```
00:00:01.932 [../src/xdg-deco.c:31] Client requested None decorations
00:00:01.932 [../src/xdg-deco.c:39] We set decorations to client
00:00:01.932 [../src/xdg-deco.c:31] Client requested server decorations
00:00:01.932 [../src/xdg-deco.c:39] We set decorations to server
```

**Comment by Consolatis** [comment]
Related: https://github.com/labwc/labwc/issues/594#issuecomment-1288132289

**Comment by Consolatis** [comment]
I had a quick look to see how complex this is to fix and found that server decorations are set and then disabled again.
That happens because `has_ssd()` in `src/xdg.c` we return `false` if the config has been set to `client` which is very much wrong (I guess).

By changing that condition to `if (!rc.xdg_shell_server_side_deco && !view->ssd_enabled) {` the server side decorations show up correctly.

We should really define what `server` and `client` config settings actually mean though, e.g. if they should overwrite the client recommended decoration variant or just serve as a fallback in case the client doesn't supply any.
