### ISSUE TITLE
swaylock failure on display hotplug

### ISSUE THREAD

**Issue by kode54** [labwc/labwc#885]
I had a situation where swaylock was left on my displays, and swayidle was also set to wlopm --off them both, and when I returned, it turned them on, and somehow swaylock had been removed from the one that doesn't usually hotplug itself when DPMS'd. I could not reproduce it though.

Hmm, I wonder if this is because of a problem with #626 being applied and in use? I'm definitely making use of the hidpi-xprop patch, which I verified doesn't apply properly to 0.16.

**Comment by johanmalm** [comment]
We added support for ext-session-lock protocol a couple of weeks ago, but if the `0.17.0` branch has not been rebased since (so does not include this).

Could you confirm that you are using the branch tracking `wlroots-0.17.0` (I think that's what you've said in OP but just want to check).

Are you able to reproduce the issue with the `master` branch (i.e. not the one tracking `0.17.0`)

**Comment by kode54** [comment]
I am using the `wlroots-0.17.0` patch, applied to `master`.

**Comment by kode54** [comment]
I have reproduced an issue, but it isn't exactly as I described. I wasn't able to make hotplugging reset the display lock, but I was able to make a display lose its display lock and also lose its swaylock surfaces, by commanding that display to change its scaling using an SSH session and wlr-randr. This is similar to my previous swayidle that commanded kanshi to restore the display modes after turning the monitors back on.

https://gist.github.com/kode54/0af4fc82ff1957cd08604aab5bef5684

Swaylock issue I filed, though it doesn't appear to be their fault:

https://github.com/swaywm/swaylock/issues/313

**Comment by Consolatis** [comment]
Short update on the situation, it seems this can not be reproduced on latest master + wlroots 0.16.x and only happens when running with the wip wlroots 0.17.x branch at #626. There might be a subtle wlroots change for 0.17 that we don't react to properly.

Behind the lock surfaces there should always be a black rectangle with the same dimension as the output itself, positioned at `0,0` of that output. We will do some more debugging with that wlroots 0.17 wip branch applied.

**Comment by johanmalm** [comment]
Can't get to an extra screen for a couple of days, but when I do I will try connecting/disconnecting to see if I can reproduce it.

**Comment by johanmalm** [comment]
I've been trying with the two scripts below be cannot reproduce this with the `master` branch.

swaylock-test

```
#!/bin/sh
swaylock-logging &
sleep 2
echo "turning off with wlopm"
wlopm --off \*
sleep 10
# (un)plug hdmi cable to second screen
wlopm --on \*
killall swaylock-logging
```

swaylock-logging

```
#!/bin/sh

(WAYLAND_DEBUG=1 swaylock -f -c 000000 2>&1 \
 	| grep -v keyboard \
	| grep -v pointer \
	> ~/swaylock_logfile) &

(while :
do
	sleep 10
	pgrep swaylock || sesame
done) &
```

**Comment by kode54** [comment]
For one thing, my primary display disconnects itself when it's powered off, then reconnects when powered on. This also causes it to reset to its default video mode, which is 3840x2160@59.997 at 1.0 scale instead of 2.0.

**Comment by jlindgren90** [comment]
@kode54 Do you still see this issue after #1141?

**Comment by johanmalm** [comment]
This might be related to the layer-surface-unmap bug on surface size change to was uncovered by the wshowkeys issue. I'll have a play with that later. I can reproduce the swaylock thing, so can test.

**Comment by kode54** [comment]
This may have been related to a stale swaylock with no session lock extension being used. It stopped happening some time ago, and also does not occur with wlroots 0.18, either. Closing as resolved.
