### ISSUE TITLE
Option to render the window decorations around the window, forcing SSD even on CSD windows

### ISSUE THREAD

**Issue by jointri** [labwc/labwc#898]
Love it or hate it, client side decorations are here to stay. And you often don't have a choice, only allowed to use CSD and not maintained by the window manager aka SSD. I have an alternative option to consider. Why not provide an option to force the decorations to be rendered around the window, rather than merely only maintained by the window manager. Fvwm would be a great example of how it is implemented: 
![example](https://user-images.githubusercontent.com/81046576/234889562-67936d08-f232-4815-9027-c3f0d3d322cf.png)
Even if the window is CSD only, the decorations you configure will still show up for the window keeping a consistent UI. You can then disable then CSD buttons such as close or maximize using the settings.ini provided in your home directory. We can't really avoid CSD, but we can certainly avoid having to have CSD ruin the overall flow of how its themed.

**Comment by Consolatis** [comment]
Proposal: a third `decoration` option in `rc.xml`: `enforceServer` which makes sure to render the SSD in all cases.

Related:
- #751
- https://github.com/labwc/labwc/pull/838#issuecomment-1478534677

In #751 it was suggested to use the to-be-written application policy framework instead of adding a new decoration state to the config. I am indifferent on that but somebody would have to do the work to implement the application policy framework first.

**Comment by Consolatis** [comment]
This should now be possible with something like this:
```xml
<windowRules>
    <windowRule identifier="*" serverDecoration="yes" />
</windowRules>
```
Please comment if it isn't working or there are issues with the new feature.
