### ISSUE TITLE
Application policy framework

### ISSUE THREAD

**Issue by m1027** [labwc/labwc#900]
Hi,

I kindly ask for an option in rc.xml to enable window settings per app.

openbox had this:

```
<applications>
<application name="Alacritty>
<maximized>yes</maximized>
<!--
<fullscreen>yes</fullscreen>
-->
</application>
</applications>
```

The current workaround is to set maximized or fullscreen (or any other option) by each app's individual configuration (if available). So for firefox like `--kiosk`, for Alacritty some internal config flag. The disadvantage of lsuch a workaround is:
- Some apps don't have such an option
- Some apps don't allow to toggle back to non-fullscreen/non-maximized state via labwc then.

Thanks

**Comment by johanmalm** [comment]
https://github.com/labwc/labwc/pull/901

I've had a go at setting up some basic infrastructure for this. I've only done `app_id` so far rather than `name`, `class`, `title`, etc

Can anyone think of a good reason to implement `<maximized>`, `<fullscreen>` as special children of `<application>`? I've just gone for `<action>` for the moment. This is a deviation from Openbox 3.6 specification, but seems a lot simpler and consistent.

I'd appreciate thoughts on when to apply the rules. I've just stuck it in the map-handler for the moment. I think that probably covers most cases, but haven't given it a lot of thought.

**Comment by johanmalm** [comment]
Try it with something like

```xml
  <applications>
    <application app_id="Alacritty">
      <action name="ToggleMaximize"/>
    </application>
  </applications>
```

**Comment by m1027** [comment]
Personally I don't care whether `<action>` is used as a child or the a property like `<maximized>`.

Well, just some thought: `<action>` confuses me slightly here as one might ask who triggers the action? But the openbox style like `<maximimized>yes</maximized>` is probably not perfectly elegant either.

As far as I remember: The only reason to set these kind of options in openbox was to change the initial appearance of application windows (which is probably the on-map event?). If you think of implementing arbitrary action binding on different events then why not name the event like in js where we have on_click and similar.

Well, these are just some thoughts...

I am very happy that you start addressing these new features! Thanks

**Comment by johanmalm** [comment]
Thanks. Great feedback.

I guess we could wrap the `<action>` in a `<onMap>` or similar to make it more intuitive. Possibly even `<onFirstMap>`.

I'll explore a bit what Openbox and other compositors such as Wayfire actually do in terms of persistence vs event-driven approaches.

Just thinking...

```xml
<applications>
    <application app_id="Alacritty" name.action.onFirstMap="Maximize" />
  </applications>
```

**Comment by Consolatis** [comment]
I am not sure what `application` means. A PID having at least one toplevel surface mapped?
I'd suggest something like `windows` instead:
```xml
<rules>
    <window identifier="chromium">
        ..
    </window>
</rules>
```

Where identifier would either be `app_id` for wayland native clients or `WM_CLASS` for xwayland clients and `*` for all windows. At a later point we could potentially add a glob filter here so something like `chrom*` would catch `chromium` and `chrome`. I personally prefer the easier glob filters vs regex filters for config files but I'd be fine with regex as well.

As for the question of directly using actions I need to think a bit about it, the idea with using event handlers which then have actions as sub nodes seems interesting and would generalize the whole thing pretty nice. So we don't have to sprinkle random conditions everywhere. We should likely have some options that a user could set as well, like preventing this window from getting valid xdg-activation tokens to prevent a situation where an application uses the xdg-activation protocol to keep its focus or request keyboard focus just because it has mouse focus.

**Comment by m1027** [comment]
Just another remark:

(1) The systematic approach

It seems to me that even `keyboard`and `mouse` sections of the config file are actually names for events (and in fact `application` in openbox was actually meaning an event: the onFirstMap event so to say).

So all in all, the configuration task is mostly binding actions to events, and keyboard hits, mouse clicks etc make no exceptions. So the assignment of actions to events would make sense to me as beeing the central thing. The config file specification could follow this idea straight forward when thinking of the xml structure.

For then fine tuning such rules by window names and similar there are different ways to bring that into play, of course. As not *all* kinds of events may be bound to windows (?) a systematic way should probably start with the event name as a parent node, while other nodes are children or node attributes.

But that's not the only possible way.

(2) The natural approach

The older openbox specification just felt kind of natural to me, too. The users might just think of keyboard, mouse and application (onMap) as their entry points when configuring their WM behaviour, and less the terms of events.

Personally I'd tend to go the systematic way but I probably haven't covered all possible real-world configuration settings. Especially when it comes to pattern matching:

(3) Rule-based approach and pattern matching

When it comes to rules and pattern matching, it's about, well, rules and their order. This normally provides the most comprehensive coverage of configuration needs. udev rules come into my mind here.

**Comment by johanmalm** [comment]
Thanks for critical review.

# XML Syntax

I agree that Openbox's `<applications>` is an odd element name in this context. Interestingly, the heading on their wiki is 'Settings for specific windows'. So, let's go with a different name;  we're taking a different approach on window-rules anyway.

Proposal below (slight variation on your suggestions, but pretty close):

```
<!-- identifier means app_id for native Wayland windows and WM_CLASS for XWayland clients -->
<windowRules>
  <windowRule identifier="Alacritty" event="onMap">
    <action name="Maximize" />
  </windowRule>
</windowRules>
```

# Globbing

I prefer globbing too and it's what Openbox does. I think regex is a bit too deep for window-rules and if there turns out to be a convincing use-case later, we could always add support then.

Also, we already use globbing in `theme.c` so can just share that function.

# EVENT DRIVEN

I'm not sure it's what either of you meant, but just to make clear, I don't particularly want to touch the `<keybind>` and `<mousebind>` logics/config. They were quite hard to get right and I think they are as simple as they can reasonably be for users without compromising functionality. From an `<actions>` perspective, I simply consider that actions can be triggered by:

1. Input events (as defined by key/mouse-binds)
2. Menus
3. Window rules (associated with events such as onMap)

# References

- Sway uses app_id/class/title and regex for their criteria, for example `for_window [app_id="telegramdesktop"]`
- Wayfire supports all-sorts... https://github.com/WayfireWM/wayfire/wiki/Configuration#window-rules
- Openbox supports name/class/role/title/type and uses globbing ("*" and "?")

# Properties

> We should likely have some options that a user could set as well though, like keeping / removing decorations or preventing this window from getting valid xdg-activation tokens to prevent a situation where an application (ab)uses the xdg-activation protocol to keep its focus or to request keyboard focus just because it has mouse focus.

@Consolatis you make a good point (as usual). We need to support properties of some sort.

In xwayland request_activate example (https://github.com/labwc/labwc/issues/874#issuecomment-1514807097), how about dealing with it like this:

- Add `bool should_handle_request_activate` in the `struct window_rule`. Default yes.
- Return early in `handle_request_activate()` if it's set to no.

```
<windowRules>
  <windowRule identifier="League*Legends">
    <shouldHandleRequestActivate>no</shouldHandleRequestActivate>
  </windowRule>
</windowRules>
```

# Excludes

If we choose the `<action>` approach, it would not be trivial to support the Openbox config below:

```
<applications>

  <!-- match all windows, and remove their decorations -->
  <application class="*">
    <decor>no</decor>
  </application>

  <!-- orage does get decorations though -->
  <application class="Orage">
    <decor>yes</decor>
  </application>

</applications>
```

Doing 'exclusion' matching isn't easy with regex either. If there is a use-case for this sort of thing, one simple approach could be to do something like: `<windowRule identifier="!foo,bar,baz">` where the ! would mean to do the action for all *EXCEPT* foo, bar and baz.

**Comment by Consolatis** [comment]
> If we choose the `<action>` approach, it would not be trivial to support the Openbox config below:

What about something like this?

```xml
<windowRules>

    <!-- match all windows, and remove their decorations -->
    <windowRule identifier="*" decorations="no" />

    <!-- orage does get decorations though, and it will start maximized -->
    <windowRule identifier="Orage" decorations="yes" event="onMap">
        <action name="ToggleMaximize" />
    </windowRule>

    <!-- Prevent focus requests by LoL and telegram -->
    <windowRule identifier="League*Legends" allowFocusRequest="no" />
    <windowRule identifier="Telegram" allowFocusRequest="no" />

</windowRules>
```

**Comment by m1027** [comment]
I like that approach.

Just some notes if you like:

- `windowRules`: I like the naming because of `window`in it. It makes it clearer that keyboard and mouse events are not covered.
- If find `identifier` is a good general naming.
- I wonder when there is the need to add `event="onMap"` and when not.
- I wonder if there was a distinct difference between something like `<windowRule> ... <action>ToggleMaximize...` and ` <window Rule ... maximize="yes"...` 

Thanks again.

**Comment by Consolatis** [comment]
> * I wonder when there is the need to add `event="onMap"` and when not.

Good point. Are there actually any other events we are interesting in, other than `onMap`? If not I guess we could just remove it and say that all actions that are sub nodes of a window rule automatically apply on map.

**Comment by Consolatis** [comment]
> Cons for option B:
> 
> * More code

true

> more alloc/free of actions, etc.

We might get away with storing a pointer to the action `struct wl_list` from the `rc.window_rules` entry instead. Although that would only work if we only have a single matching entry with `!wl_list_empty(action list)`..

I think 2b would be better long term as something like configuring decorations to be `server`, then saying all windows should have no decorations unless the app_id is `foot` would be a valid use-case. That doesn't seem possible with Option 2a.

Regarding decision 1: I didn't make up my mind yet.
Another pro for 1a would be that users could launch external scripts whenever they open some specific application.

**Comment by johanmalm** [comment]
Just thinking allowed... If we add the following:

```
struct window_rule_actions {
	enum window_rule_event event;
	struct wl_list actions;
};

struct window_rule_properties {
	bool allowFocusRequest;
}
```


...then we get

```
struct window_rule {
	char *identifier;
	struct window_rule_actions actions;
	struct window_rule_properties properties;
	struct wl_list link; /* struct rcxml.window_rules */
};
```


...and to `struct view` we could add 

	- One `struct window_rule_properties`
	- wl_list of `struct window_rule_actions` with pointers to the ones held in global `rc`


Maybe something like:


```
struct view_rule_actions {
	struct window_rule_actions *actions;
	struct wl_list link;	/* view.rule->actions */
};


struct view {
	...

	struct {
		struct window_rule_properties properties;
		struct wl_list actions;
	} rule;

	...
}
```

**Comment by Consolatis** [comment]
This seems nearly identitcal to what I proposed above with the difference of using a dedidcated `struct window_properties` and an enum for the event type (which is a good idea if we intend to support more than the `onMap` event).

We have an issue with the properties though, we can't really use `bool` here because we need a 3-state value: there is a difference between specifying `decorations` as `false` and not specifying it at all. So maybe something like this?
```c
enum property {
    PROP_UNSPEC = 0,
    PROP_TRUE,
    PROP_FALSE
};
```

**Comment by johanmalm** [comment]
Yes - just building on what you said.

I could do a server-deco test case with the 2a approach to just see what it looks like. Implementing 2b would require me to focus for a lot longer :see_no_evil:

**Comment by johanmalm** [comment]
Review of #901 would be appreciated.

'maximize` and `fullscreen` actions not yet implemented, but should be very quick and easy when we agreed on implementation approach.

**Comment by m1027** [comment]
Congratulation and many thanks for the new rules based window configuration!

Maximization on window mapping works great!

Whenever you find time to add an `action` to trigger `Fullscreen`, too, this issue can be closed.

**Comment by Consolatis** [comment]
`ToggleFullscreen` should work
