### ISSUE TITLE
Consider replacing use of "C99 Reserved Identifiers"

### ISSUE THREAD

**Issue by domo141** [labwc/labwc#918]
According to some hard-to-read documents about reserved identifiers in C found in the (wild) Internet, 

"All identifiers that begin with an underscore and either an uppercase letter or another underscore are always reserved for any use."

That would mean that the __LAB* (or, in some cases, just \_\_\*) prefix in labwc
header files (*.h) would be using "reserved identifiers".

It was discussed in IRC, that possibly changing these to LABWC_INCLUDE_GUARD_* could be an option.

There are (still probably) quite a few projects that do use these reserved identifiers in their codebase (old, or -- as this information is not so clearly
avalable, in newer projects, too) -- and some of those are keep having those.

OTOH. e.g. zephyrproject changed their include guards which were using this reserved "syntax" between versions 1.14 and 2.7.

SO, if there is interest to make such a change in this repository, too, 
the following information may be useful (did I submit the PR or someone else(tm)):

A bit of grepping and then experimentation shows that:

`git grep -l ' __LAB' | xargs sed -i 's/ __LAB[CW]*/ LABWC_INCLUDE_GUARD/'`

would make this particular change to 40 of 46 (header) files in question 

`(cd include && exec sed -i 's/ __/ LABWC_INCLUDE_GUARD_/'  debug.h resistance.h window-rules.h)`

would change 3 files that did not have __LAB nor __LABWC in include guard.

then the (remaining 3 files `include/common/graphic-helpers.h`,  `include/common/list.h` and `include/common/scene-helpers.h` does not have include guards at all -- easy to edit "manually" if so desired...

**Comment by johanmalm** [comment]
Looks like we have some header guards to tidy up regardless of the underscore issue.

I'm happy to change the prefix to `LABWC_` instead of `__LABWC__` but I don't want to make the code ugly (e.g. `LABWC_INCLUDE_GUARD_`) to avoid a name-clash that will never happen (and if it did, the compile will warn and it's not that hard to fix).

I'm guessing the rule is to allow the C language to add keywords without clashing with old code-bases. So far they look like `_Alignof`, `_Atomic`, `_Statis_assert` and so on. Now, I like compliance, but a lot of C codebases have include guards like ours and I think they chances of the C standard committee adding a keyword beginning with `__LABWC` is pretty low :smile:

**Comment by Consolatis** [comment]
I don't think it would make the code ugly, its just two long strongs on top of the headers that nobody ever reads.
