### ISSUE TITLE
build optional org_kde_kwin_idle layer?

### ISSUE THREAD

**Issue by CaptainBloodz** [labwc/labwc#982]
How far is the labwc stack to support such an option?

**Comment by johanmalm** [comment]
Do you mean the kde-idle protocol? https://wayland.app/protocols/kde-idle
If so, we already support that.

**Comment by CaptainBloodz** [comment]
Sorry for being too laconic...
I meant as a build option to shrink binary size when not required.

**Comment by Consolatis** [comment]
Specifically the idle protocols are so minimal that it really doesn't matter in regards to the binary size.
If you want to save binary size, building in release mode + linking to a system wide install of wlroots instead of static linking + stripping the binary would likely be the better approach. You could also disable xwayland.
